
<center><img src='../img/data_explorer.png' alt='Data Explorer' height='300'/></center>


# Initial Exploration and Selection of Medical Datasets for Machine Learning Project

This notebook serves as an initial exploration of various medical datasets to identify the most relevant ones for a machine learning project. 

I will conduct a preliminary quick analysis to understand each dataset's structure, data quality, variable types, and any relevant attributes that may be critical for predictive modeling. By examining features such as data completeness, feature correlations, and target distribution. This exploratory phase will provide a foundation for a datasets selection and streamline the subsequent data preprocessing and modeling stages. Only one dataset will be selected for this project, but the remaining datasets are available for potential use in future researchs.

In [1]:
import os
import sys
import zipfile

import kagglehub
import pandas as pd
import pyreadstat
import requests

from ucimlrepo import fetch_ucirepo

# add "src" path
root_path = os.path.abspath(os.path.join(os.getcwd(), '..')) 
if os.path.exists(root_path) and root_path not in sys.path: 
    sys.path.append(root_path)
                        
from utils import datascience as ds

c:\Users\Lander\Documents\GitHub\portfolio\heart_disease_classifier\.venv_heart\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Breast Cancer Wisconsin (Diagnostic)

Wolberg, W., Mangasarian, O., Street, N., & Street, W. (1993). Breast Cancer Wisconsin (Diagnostic Dataset). [UCI Machine Learning Repository](https://doi.org/10.24432/C5DW2B).

In [2]:
# fetch dataset 
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
  
# data (as pandas dataframes) 
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets 
  
print(breast_cancer_wisconsin_diagnostic.metadata) 
display(X.head())
display(breast_cancer_wisconsin_diagnostic.variables) 
ds.get_cardinality(X)

{'uci_id': 17, 'name': 'Breast Cancer Wisconsin (Diagnostic)', 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic', 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv', 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 569, 'num_features': 30, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Diagnosis'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1993, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5DW2B', 'creators': ['William Wolberg', 'Olvi Mangasarian', 'Nick Street', 'W. Street'], 'intro_paper': {'ID': 230, 'type': 'NATIVE', 'title': 'Nuclear feature extraction for breast tumor diagnosis', 'authors': 'W. Street, W. Wolberg, O. Mangasarian', 'venue': 'Electronic imaging', 'year': 1993, 'journal': None, 'DOI': '10.1117/12.148698', 'URL': 'https://www.semanticscholar.org/paper/53f0fbb425bc14468eb3bf96b2e1d41ba8087f36', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass.  They describe characteristics of the cell nuclei present in the image. A few of the images can be found at http://www.cs.wisc.edu/~street/images/\r\n\r\nSeparating plane described above was obtained using Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree Construction Via Linear Programming." Proceedings of the 4th Midwest Artificial Intelligence and Cognitive Science Society, pp. 97-101, 1992], a classification method which uses linear programming to construct a decision tree.  Relevant features were selected using an exhaustive search in the space of 1-4 features and 1-3 separating planes.\r\n\r\nThe actual linear program used to obtain the separating plane in the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].\r\n\r\nThis database is also available through the UW CS ftp server:\r\nftp ftp.cs.wisc.edu\r\ncd math-prog/cpo-dataset/machine-learn/WDBC/', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1) ID number\r\n2) Diagnosis (M = malignant, B = benign)\r\n3-32)\r\n\r\nTen real-valued features are computed for each cell nucleus:\r\n\r\n\ta) radius (mean of distances from center to points on the perimeter)\r\n\tb) texture (standard deviation of gray-scale values)\r\n\tc) perimeter\r\n\td) area\r\n\te) smoothness (local variation in radius lengths)\r\n\tf) compactness (perimeter^2 / area - 1.0)\r\n\tg) concavity (severity of concave portions of the contour)\r\n\th) concave points (number of concave portions of the contour)\r\n\ti) symmetry \r\n\tj) fractal dimension ("coastline approximation" - 1)', 'citation': None}}

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

,name,role,type,demographic,description,units,missing_values
0,ID,ID,Categorical,None,None,None,no
1,Diagnosis,Target,Categorical,None,None,None,no
2,radius1,Feature,Continuous,None,None,None,no
3,texture1,Feature,Continuous,None,None,None,no
4,perimeter1,Feature,Continuous,None,None,None,no
5,area1,Feature,Continuous,None,None,None,no
6,smoothness1,Feature,Continuous,None,None,None,no
7,compactness1,Feature,Continuous,None,None,None,no
8,concavity1,Feature,Continuous,None,None,None,no
9,concave_points1,Feature,Continuous,None,None,None,no
10,symmetry1,Feature,Continuous,None,None,None,no
11,fractal_dimension1,Feature,Continuous,None,None,None,no
12,radius2,Feature,Continuous,None,None,None,no
13,texture2,Feature,Continuous,None,None,None,no
14,perimeter2,Feature,Continuous,None,None,None,no
15,area2,Feature,Continuous,None,None,None,no
16,smoothness2,Feature,Continuous,None,None,None,no
17,compactness2,Feature,Continuous,None,None,None,no
18,concavity2,Feature,Continuous,None,None,None,no
19,concave_points2,Feature,Continuous,None,None,None,no
20,symmetry2,Feature,Continuous,None,None,None,no
21,fractal_dimension2,Feature,Continuous,None,None,None,no
22,radius3,Feature,Continuous,None,None,None,no
23,texture3,Feature,Continuous,None,None,None,no
24,perimeter3,Feature,Continuous,None,None,None,no
25,area3,Feature,Continuous,None,None,None,no
26,smoothness3,Feature,Continuous,None,None,None,no
27,compactness3,Feature,Continuous,None,None,None,no
28,concavity3,Feature,Continuous,None,None,None,no
29,concave_points3,Feature,Continuous,None,None,None,no
30,symmetry3,Feature,Continuous,None,None,None,no
31,fractal_dimension3,Feature,Continuous,None,None,None,no

pandas.DataFrame shape: (569, 30)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
radius1,456,80.140598,0,0.0,float64,Numeric - Continuous
texture1,479,84.182777,0,0.0,float64,Numeric - Continuous
perimeter1,522,91.739895,0,0.0,float64,Numeric - Continuous
area1,539,94.727592,0,0.0,float64,Numeric - Continuous
smoothness1,474,83.304042,0,0.0,float64,Numeric - Continuous
compactness1,537,94.376098,0,0.0,float64,Numeric - Continuous
concavity1,537,94.376098,0,0.0,float64,Numeric - Continuous
concave_points1,542,95.254833,0,0.0,float64,Numeric - Continuous
symmetry1,432,75.922671,0,0.0,float64,Numeric - Continuous
fractal_dimension1,499,87.697715,0,0.0,float64,Numeric - Continuous
radius2,540,94.903339,0,0.0,float64,Numeric - Continuous
texture2,519,91.212654,0,0.0,float64,Numeric - Continuous
perimeter2,533,93.673111,0,0.0,float64,Numeric - Continuous
area2,528,92.794376,0,0.0,float64,Numeric - Continuous
smoothness2,547,96.133568,0,0.0,float64,Numeric - Continuous
compactness2,541,95.079086,0,0.0,float64,Numeric - Continuous
concavity2,533,93.673111,0,0.0,float64,Numeric - Continuous
concave_points2,507,89.103691,0,0.0,float64,Numeric - Continuous
symmetry2,498,87.521968,0,0.0,float64,Numeric - Continuous
fractal_dimension2,545,95.782074,0,0.0,float64,Numeric - Continuous
radius3,457,80.316344,0,0.0,float64,Numeric - Continuous
texture3,511,89.806678,0,0.0,float64,Numeric - Continuous
perimeter3,514,90.333919,0,0.0,float64,Numeric - Continuous
area3,544,95.606327,0,0.0,float64,Numeric - Continuous
smoothness3,411,72.231986,0,0.0,float64,Numeric - Continuous
compactness3,529,92.970123,0,0.0,float64,Numeric - Continuous
concavity3,539,94.727592,0,0.0,float64,Numeric - Continuous
concave_points3,492,86.467487,0,0.0,float64,Numeric - Continuous
symmetry3,500,87.873462,0,0.0,float64,Numeric - Continuous
fractal_dimension3,535,94.024605,0,0.0,float64,Numeric - Continuous

# Breast Cancer Wisconsin (Original)

W. Wolberg. "Breast Cancer Wisconsin (Original)," UCI Machine Learning Repository, 1990. [Online]. Available: https://doi.org/10.24432/C5HP4Z.

In [3]:
 # fetch dataset 
breast_cancer_wisconsin_original = fetch_ucirepo(id=15) 
  
# data (as pandas dataframes) 
X = breast_cancer_wisconsin_original.data.features 
y = breast_cancer_wisconsin_original.data.targets 
  
print(breast_cancer_wisconsin_original.metadata) 
display(X.head())
display(breast_cancer_wisconsin_original.variables) 
ds.get_cardinality(X)

{'uci_id': 15, 'name': 'Breast Cancer Wisconsin (Original)', 'repository_url': 'https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original', 'data_url': 'https://archive.ics.uci.edu/static/public/15/data.csv', 'abstract': 'Original Wisconsin Breast Cancer Database', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 699, 'num_features': 9, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['Class'], 'index_col': ['Sample_code_number'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1990, 'last_updated': 'Sun Mar 10 2024', 'dataset_doi': '10.24432/C5HP4Z', 'creators': ['WIlliam Wolberg'], 'intro_paper': None, 'additional_info': {'summary': "Samples arrive periodically as Dr. Wolberg reports his clinical cases. The database therefore reflects this chronological grouping of the data. This grouping information appears immediately below, having been removed from the data itself:\r\n\r\nGroup 1: 367 instances (January 1989)\r\nGroup 2:  70 instances (October 1989)\r\nGroup 3:  31 instances (February 1990)\r\nGroup 4:  17 instances (April 1990)\r\nGroup 5:  48 instances (August 1990)\r\nGroup 6:  49 instances (Updated January 1991)\r\nGroup 7:  31 instances (June 1991)\r\nGroup 8:  86 instances (November 1991)\r\n-----------------------------------------\r\nTotal:   699 points (as of the donated datbase on 15 July 1992)\r\n\r\nNote that the results summarized above in Past Usage refer to a dataset of size 369, while Group 1 has only 367 instances.  This is because it originally contained 369 instances; 2 were removed.  The following statements summarizes changes to the original Group 1's set of data:\r\n\r\n#####  Group 1 : 367 points: 200B 167M (January 1989)\r\n\r\n#####  Revised Jan 10, 1991: Replaced zero bare nuclei in 1080185 & 1187805\r\n\r\n#####  Revised Nov 22,1991: Removed 765878,4,5,9,7,10,10,10,3,8,1 no record\r\n#####                  : Removed 484201,2,7,8,8,4,3,10,3,4,1 zero epithelial\r\n#####                  : Changed 0 to 1 in field 6 of sample 1219406\r\n#####                  : Changed 0 to 1 in field 8 of following sample:\r\n#####                  : 1182404,2,3,1,1,1,2,0,1,1,1", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1. Sample code number:            id number\r\n2. Clump Thickness:               1 - 10\r\n3. Uniformity of Cell Size:       1 - 10\r\n4. Uniformity of Cell Shape:      1 - 10\r\n5. Marginal Adhesion:             1 - 10\r\n6. Single Epithelial Cell Size:   1 - 10\r\n7. Bare Nuclei:                   1 - 10\r\n8. Bland Chromatin:               1 - 10\r\n9. Normal Nucleoli:               1 - 10\r\n10. Mitoses:                       1 - 10\r\n11. Class:                        (2 for benign, 4 for malignant)', 'citation': 'This breast cancer databases was obtained from the University of Wisconsin Hospitals, Madison from Dr. William H. Wolberg.  If you publish results when using this database, then please include this information in your acknowledgements.  Also, please cite one or more of:\n1. O. L. Mangasarian and W. H. Wolberg: "Cancer diagnosis via linear programming", SIAM News, Volume 23, Number 5, September 1990, pp 1 & 18.\n2. William H. Wolberg and O.L. Mangasarian: "Multisurface method of pattern separation for medical diagnosis applied to breast cytology", Proceedings of the National Academy of Sciences, U.S.A., Volume 87, December 1990, pp 9193-9196.\n3. O. L. Mangasarian, R. Setiono, and W.H. Wolberg: "Pattern recognition via linear programming: Theory and application to medical diagnosis", in: "Large-scale numerical optimization", Thomas F. Coleman and Yuying Li, editors, SIAM Publications, Philadelphia 1990, pp 22-30.\n4. K. P. Bennett & O. L. Mangasarian: "Robust linear programming discrimination of two linearly inseparable sets", Optimization Methods and Software 1, 1992, 23-34 (Gordon & Breach Science Publishers).'}}

,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
0,5,1,1,1,2,1.0,3,1,1
1,5,4,4,5,7,10.0,3,2,1
2,3,1,1,1,2,2.0,3,1,1
3,6,8,8,1,3,4.0,3,7,1
4,4,1,1,3,2,1.0,3,1,1

,name,role,type,demographic,description,units,missing_values
0,Sample_code_number,ID,Categorical,None,None,None,no
1,Clump_thickness,Feature,Integer,None,None,None,no
2,Uniformity_of_cell_size,Feature,Integer,None,None,None,no
3,Uniformity_of_cell_shape,Feature,Integer,None,None,None,no
4,Marginal_adhesion,Feature,Integer,None,None,None,no
5,Single_epithelial_cell_size,Feature,Integer,None,None,None,no
6,Bare_nuclei,Feature,Integer,None,None,None,yes
7,Bland_chromatin,Feature,Integer,None,None,None,no
8,Normal_nucleoli,Feature,Integer,None,None,None,no
9,Mitoses,Feature,Integer,None,None,None,no
10,Class,Target,Binary,None,"2 = benign, 4 = malignant",None,no

pandas.DataFrame shape: (699, 9)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
Clump_thickness,10,1.430615,0,0.0,int64,Numeric - Discrete
Uniformity_of_cell_size,10,1.430615,0,0.0,int64,Numeric - Discrete
Uniformity_of_cell_shape,10,1.430615,0,0.0,int64,Numeric - Discrete
Marginal_adhesion,10,1.430615,0,0.0,int64,Numeric - Discrete
Single_epithelial_cell_size,10,1.430615,0,0.0,int64,Numeric - Discrete
Bare_nuclei,10,1.430615,16,2.288984,float64,Numeric - Discrete
Bland_chromatin,10,1.430615,0,0.0,int64,Numeric - Discrete
Normal_nucleoli,10,1.430615,0,0.0,int64,Numeric - Discrete
Mitoses,9,1.287554,0,0.0,int64,Categoric

# 2022 BRFSS (Behavioral Risk Factor Surveillance System) Survey Data and Documentation

https://www.cdc.gov/brfss/annual_data/annual_2020.html

https://www.cdc.gov/brfss/annual_data/annual_2022.html

In [4]:
# 2020 year

URL = 'https://www.cdc.gov/brfss/annual_data/2020/files/LLCP2020XPT.zip' 
DATA_RAW = '../data/raw/'
ZIP_FOLDER = 'LLCP2020XPT.zip'

unzip_folder = ZIP_FOLDER[:-4]
fname = ZIP_FOLDER[:-7] + '.XPT'
zip_folder_path = DATA_RAW + ZIP_FOLDER
unzip_folder_path = DATA_RAW + unzip_folder
file_path = unzip_folder_path + '/' + fname

# print(zip_folder_path)
# print(unzip_folder_path)
# print(file_path)

response = requests.get(URL)
with open(zip_folder_path, 'wb') as file:
    file.write(response.content)

with zipfile.ZipFile(zip_folder_path, 'r') as zip_ref:
    zip_ref.extractall(unzip_folder_path) 

df_brfss_2020, meta = pyreadstat.read_xport(file_path, encoding='latin1')

display(df_brfss_2020)

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_RFPSA23,_CLNSCPY,_SGMSCPY,_SGMS10Y,_RFBLDS4,_STOLDNA,_VIRCOLN,_SBONTIM,_CRCREC1,_AIDTST4
0,1.0,1.0,01042020,01,04,2020,1100.0,2020000001,2.020000e+09,1.0,...,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
1,1.0,1.0,02072020,02,07,2020,1200.0,2020000002,2.020000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
2,1.0,1.0,01232020,01,23,2020,1100.0,2020000003,2.020000e+09,1.0,...,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0
3,1.0,1.0,01092020,01,09,2020,1100.0,2020000004,2.020000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,1.0,1.0,01042020,01,04,2020,1100.0,2020000005,2.020000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401953,72.0,11.0,02192021,02,19,2021,1100.0,2020004940,2.020005e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
401954,72.0,11.0,02142021,02,14,2021,1100.0,2020004941,2.020005e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
401955,72.0,11.0,02142021,02,14,2021,1100.0,2020004942,2.020005e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
401956,72.0,11.0,03172021,03,17,2021,1100.0,2020004943,2.020005e+09,NaN,...,1.0,1.0,3.0,3.0,1.0,3.0,3.0,2.0,1.0,1.0
401957,72.0,11.0,02182021,02,18,2021,1100.0,2020004944,2.020005e+09,NaN,...,NaN,1.0,3.0,3.0,1.0,3.0,3.0,2.0,1.0,1.0

In [5]:
# 2022 year

URL = 'https://www.cdc.gov/brfss/annual_data/2022/files/LLCP2022XPT.zip' 
DATA_RAW = '../data/raw/'
ZIP_FOLDER = 'LLCP2022XPT.zip'

unzip_folder = ZIP_FOLDER[:-4]
fname = ZIP_FOLDER[:-7] + '.XPT'
zip_folder_path = DATA_RAW + ZIP_FOLDER
unzip_folder_path = DATA_RAW + unzip_folder
file_path = unzip_folder_path + '/' + fname

response = requests.get(URL)
with open(zip_folder_path, 'wb') as file:
    file.write(response.content)

with zipfile.ZipFile(zip_folder_path, 'r') as zip_ref:
    zip_ref.extractall(unzip_folder_path) 

df_brfss_2022, meta = pyreadstat.read_xport(file_path, encoding='latin1')

display(df_brfss_2022)

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_SMOKGRP,_LCSREC,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,1.0,02032022,02,03,2022,1100.0,2022000001,2.022000e+09,1.0,...,4.0,NaN,2.0,0.0,1.0,0.0,1.0,1.0,2.0,2.0
1,1.0,1.0,02042022,02,04,2022,1100.0,2022000002,2.022000e+09,1.0,...,4.0,NaN,2.0,0.0,1.0,0.0,1.0,2.0,2.0,2.0
2,1.0,1.0,02022022,02,02,2022,1100.0,2022000003,2.022000e+09,1.0,...,4.0,NaN,2.0,0.0,1.0,0.0,1.0,NaN,NaN,2.0
3,1.0,1.0,02032022,02,03,2022,1100.0,2022000004,2.022000e+09,1.0,...,3.0,2.0,2.0,0.0,1.0,0.0,1.0,9.0,9.0,2.0
4,1.0,1.0,02022022,02,02,2022,1100.0,2022000005,2.022000e+09,1.0,...,4.0,NaN,1.0,10.0,1.0,140.0,1.0,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445127,78.0,11.0,12192022,12,19,2022,1100.0,2022001527,2.022002e+09,NaN,...,4.0,NaN,7.0,900.0,9.0,99900.0,9.0,NaN,NaN,1.0
445128,78.0,11.0,12212022,12,21,2022,1100.0,2022001528,2.022002e+09,NaN,...,4.0,NaN,2.0,0.0,1.0,0.0,1.0,NaN,NaN,1.0
445129,78.0,11.0,11292022,11,29,2022,1100.0,2022001529,2.022002e+09,NaN,...,1.0,NaN,7.0,900.0,9.0,99900.0,9.0,2.0,2.0,2.0
445130,78.0,11.0,12082022,12,08,2022,1100.0,2022001530,2.022002e+09,NaN,...,4.0,NaN,2.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0
445131,78.0,11.0,12142022,12,14,2022,1100.0,2022001531,2.022002e+09,NaN,...,3.0,NaN,1.0,50.0,2.0,99900.0,9.0,NaN,NaN,2.0

In [6]:
# cardinality and values of variables used to categorize or classify respondents (begin with "_")
i = 0
for column in df_brfss_2022.columns:
    if column.startswith('_'):
        print(df_brfss_2022[column].value_counts())
        print()
        i += 1

print(i)

_STATE
53.0    26152
36.0    17800
27.0    16821
39.0    16487
24.0    16418
48.0    14245
12.0    13393
55.0    11276
20.0    11247
25.0    11029
6.0     10952
23.0    10646
18.0    10466
51.0    10417
4.0     10185
26.0    10058
45.0    10037
49.0     9826
9.0      9784
8.0      9365
13.0     9236
19.0     8949
50.0     8811
34.0     8209
15.0     7747
31.0     7473
29.0     7438
46.0     7424
30.0     7048
33.0     6757
16.0     6280
44.0     5893
2.0      5865
40.0     5775
41.0     5756
22.0     5629
72.0     5509
5.0      5309
47.0     5266
54.0     4981
35.0     4758
42.0     4582
1.0      4506
37.0     4505
28.0     4239
38.0     4153
56.0     4142
17.0     4056
21.0     4023
10.0     3987
11.0     3237
32.0     3188
66.0     2266
78.0     1531
Name: count, dtype: int64

_PSU
2.022000e+09    54
2.022000e+09    54
2.022000e+09    54
2.022000e+09    54
2.022000e+09    54
                ..
2.022026e+09     1
2.022026e+09     1
2.022026e+09     1
2.022026e+09     1
2.022026e+09     1
Name: count, Length: 26152, dtype: int64

_METSTAT
1.0    318082
2.0    117642
Name: count, dtype: int64

_URBSTAT
1.0    380732
2.0     54992
Name: count, dtype: int64

_STSTR
272051.0    5875
722011.0    4779
242011.0    4185
272041.0    3850
342061.0    3806
            ...
252049.0       1
421052.0       1
122399.0       1
122179.0       1
12069.0        1
Name: count, Length: 2263, dtype: int64

_STRWT
10.358928     7401
7.973648      6611
35.910980     6251
34.399036     5691
37.031190     5296
              ...
2.756005         1
13.742895        1
25.293266        1
401.050996       1
133.856311       1
Name: count, Length: 1640, dtype: int64

_RAWRAKE
1.000000    392702
2.000000     41864
3.000000      6371
4.000000      1848
0.500000       950
5.000000       656
0.666667       257
0.333333       226
1.500000       205
2.500000        24
1.333333        23
1.666667         6
Name: count, dtype: int64

_WT2RAKE
10.358928     7401
7.973648      6611
35.910980     6251
34.399036     5691
37.031190     5296
              ...
10.807548        1
187.303474       1
15.608623        1
2.254579         1
0.754023         1
Name: count, Length: 5383, dtype: int64

_IMPRACE
1.0    333514
5.0     42977
2.0     35876
3.0     13487
6.0     12158
4.0      7120
Name: count, dtype: int64

_CHISPNC
9.0    266763
2.0     46997
1.0     10549
Name: count, dtype: int64

_CRACE2
1.0     41818
2.0      5933
6.0      3464
99.0     3287
4.0      2381
3.0      1653
77.0      933
88.0      859
5.0       518
Name: count, dtype: int64

_CPRACE2
1.0     42913
2.0      6560
99.0     3527
4.0      2815
3.0      1798
77.0     1543
5.0       818
7.0        12
6.0         4
Name: count, dtype: int64

_CLLCPWT
218.319190     412
36.209652      375
228.781560     206
80.212906      182
174.301031     111
              ...
1886.654479      1
2040.515098      1
9072.893654      1
3636.611118      1
3688.638111      1
Name: count, Length: 20257, dtype: int64

_DUALUSE
9.0    287103
1.0     82429
2.0     75600
Name: count, dtype: int64

_DUALCOR
0.343649    4631
0.656351    4498
0.315714    3910
0.684286    3817
0.363511    3532
            ...
0.185361     352
0.630877     314
0.202781     292
0.280612     287
0.369123     168
Name: count, Length: 108, dtype: int64

_LLCPWT2
198.947967     4669
383.166215     4254
282.666799     3946
904.430379     3318
433.446212     3256
               ...
439.838913        1
328.117032        1
47.624227         1
7046.507459       1
927.018011        1
Name: count, Length: 12867, dtype: int64

_LLCPWT
203.084451    141
155.211977    122
183.671403    119
222.167350    105
149.933365    102
             ...
624.745780      1
211.348446      1
425.092890      1
701.314346      1
390.541348      1
Name: count, Length: 254189, dtype: int64

_RFHLTH
1.0    363920
2.0     80014
9.0      1198
Name: count, dtype: int64

_PHYS14D
1.0    267819
2.0    108312
3.0     58074
9.0     10927
Name: count, dtype: int64

_MENT14D
1.0    265229
2.0    110616
3.0     60220
9.0      9067
Name: count, dtype: int64

_HLTHPLN
1.0    404229
2.0     23018
9.0     17885
Name: count, dtype: int64

_HCVU652
1.0    244591
9.0    178939
2.0     21602
Name: count, dtype: int64

_TOTINDA
1.0    337559
2.0    106480
9.0      1093
Name: count, dtype: int64

_EXTETH3
1.0    233455
2.0    200317
9.0     11360
Name: count, dtype: int64

_ALTETH3
1.0    136179
2.0     16726
9.0     15514
Name: count, dtype: int64

_DENVST3
1.0    292408
2.0    145703
9.0      7017
Name: count, dtype: int64

_MICHD
2.0    400360
1.0     39751
Name: count, dtype: int64

_LTASTH1
1.0    376665
2.0     66694
9.0      1773
Name: count, dtype: int64

_CASTHM1
1.0    395613
2.0     45659
9.0      3860
Name: count, dtype: int64

_ASTHMS1
3.0    376665
1.0     45659
2.0     18948
9.0      3860
Name: count, dtype: int64

_DRDXAR2
2.0    291351
1.0    151148
Name: count, dtype: int64

_PRACE2
1.0     351032
2.0      41522
4.0      14836
3.0      10147
99.0      8593
88.0      8474
77.0      4781
5.0       4070
7.0       1664
Name: count, dtype: int64

_MRACE2
1.0     346771
2.0      39984
4.0      13838
6.0      10590
3.0       9051
99.0      8593
88.0      8474
77.0      4781
5.0       3039
Name: count, dtype: int64

_HISPANC
2.0    396631
1.0     42917
9.0      5584
Name: count, dtype: int64

_RACE1
1.0    320421
8.0     42917
2.0     35446
9.0     14055
4.0     13347
7.0      9578
3.0      6952
5.0      2414
Name: count, dtype: int64

_RACEG22
1.0    320421
2.0    110654
9.0     14055
Name: count, dtype: int64

_RACEGR4
1.0    320421
5.0     42917
2.0     35446
3.0     22713
9.0     14055
4.0      9578
Name: count, dtype: int64

_RACEPR1
1.0    333514
7.0     42977
2.0     35876
4.0     13487
6.0      9744
3.0      7120
5.0      2414
Name: count, dtype: int64

_SEX
2.0    235894
1.0    209238
Name: count, dtype: int64

_AGEG5YR
10.0    47099
9.0     44511
11.0    43472
8.0     36821
13.0    36251
7.0     33644
12.0    32518
5.0     29942
6.0     28531
4.0     28526
1.0     26941
3.0     25807
2.0     21990
14.0     9079
Name: count, dtype: int64

_AGE65YR
1.0    276713
2.0    159340
3.0      9079
Name: count, dtype: int64

_AGE80
80.0    36253
65.0    10421
70.0    10371
67.0     9652
68.0     9351
        ...
22.0     3997
20.0     3847
21.0     3837
19.0     3558
18.0     3362
Name: count, Length: 63, dtype: int64

_AGE_G
6.0    161451
5.0     82740
4.0     66984
3.0     59174
2.0     47840
1.0     26943
Name: count, dtype: int64

_BMI5
2663.0    4262
2746.0    3277
2441.0    3188
2744.0    3128
2712.0    3123
          ...
4803.0       1
3856.0       1
4264.0       1
5920.0       1
8217.0       1
Name: count, Length: 3985, dtype: int64

_BMI5CAT
3.0    139995
4.0    132577
2.0    116976
1.0      6778
Name: count, dtype: int64

_RFBMI5
2.0    272572
1.0    123754
9.0     48806
Name: count, dtype: int64

_CHLDCNT
1.0    321907
2.0     46241
3.0     37923
4.0     15975
9.0     14464
5.0      5521
6.0      3100
Name: count, dtype: int64

_EDUCAG
4.0    187496
3.0    120252
2.0    108990
1.0     26011
9.0      2383
Name: count, dtype: int64

_INCOMG1
5.0    107584
9.0     96047
6.0     72883
4.0     46831
3.0     42294
2.0     34643
7.0     23478
1.0     21372
Name: count, dtype: int64

_RFMAM22
1.0    119317
2.0     48196
9.0     13727
Name: count, dtype: int64

_MAM5023
1.0    79719
2.0    22957
Name: count, dtype: int64

_HADCOLN
1.0    207648
2.0     77681
Name: count, dtype: int64

_CLNSCP1
1.0    144417
3.0     65264
2.0     12271
Name: count, dtype: int64

_HADSIGM
2.0    253768
1.0     31561
Name: count, dtype: int64

_SGMSCP1
3.0    203384
1.0      9848
2.0      8981
Name: count, dtype: int64

_SGMS101
3.0    203384
1.0     12648
2.0      6181
Name: count, dtype: int64

_RFBLDS5
3.0    183001
2.0     21725
1.0     15497
Name: count, dtype: int64

_STOLDN1
3.0    211140
1.0      6996
2.0      1671
Name: count, dtype: int64

_VIRCOL1
3.0    213602
1.0      4263
2.0      1749
Name: count, dtype: int64

_SBONTI1
3.0    166034
2.0     48286
1.0      1079
Name: count, dtype: int64

_CRCREC2
1.0    155370
3.0     50873
2.0     15848
Name: count, dtype: int64

_SMOKER3
4.0    245955
3.0    113774
1.0     36003
9.0     35462
2.0     13938
Name: count, dtype: int64

_RFSMOK3
1.0    359729
2.0     49941
9.0     35462
Name: count, dtype: int64

_CURECI2
1.0    387356
9.0     35660
2.0     22116
Name: count, dtype: int64

_YRSSMOK
10.0    4888
5.0     4153
20.0    4008
12.0    3989
7.0     3873
        ...
80.0       2
88.0       1
85.0       1
97.0       1
87.0       1
Name: count, Length: 88, dtype: int64

_PACKDAY
1.00     42344
0.50     33105
0.25     11559
0.75      9197
2.00      6820
         ...
13.50        1
12.65        1
10.05        1
11.25        1
4.35         1
Name: count, Length: 124, dtype: int64

_PACKYRS
1.0      9437
2.0      7783
3.0      6376
4.0      5707
5.0      5665
         ...
142.0       1
312.0       1
287.0       1
485.0       1
274.0       1
Name: count, Length: 282, dtype: int64

_YRSQUIT
1.0     4738
2.0     4147
3.0     3573
10.0    3242
5.0     3183
        ...
80.0       2
84.0       1
88.0       1
81.0       1
83.0       1
Name: count, Length: 84, dtype: int64

_SMOKGRP
4.0    245955
3.0    127270
1.0     22620
2.0     13825
Name: count, dtype: int64

_LCSREC
2.0    46510
1.0     4943
Name: count, dtype: int64

_RFBING6
1.0    337114
2.0     56916
9.0     51102
Name: count, dtype: int64

_DRNKWK2
0.0        188832
99900.0     49705
23.0        20646
47.0        18325
93.0        12104
            ...
3220.0          1
6090.0          1
6860.0          1
22500.0         1
12800.0         1
Name: count, Length: 279, dtype: int64

_RFDRHV8
1.0    369122
9.0     49705
2.0     26305
Name: count, dtype: int64

_FLSHOT7
1.0    100950
2.0     43777
9.0     23692
Name: count, dtype: int64

_PNEUMO3
1.0    100859
2.0     39370
9.0     28190
Name: count, dtype: int64

_AIDTST4
2.0    249919
1.0    129086
9.0     19892
Name: count, dtype: int64

76

In [7]:
meta.column_labels

['STATE FIPS CODE',
 'FILE MONTH',
 'INTERVIEW DATE',
 'INTERVIEW MONTH',
 'INTERVIEW DAY',
 'INTERVIEW YEAR',
 'FINAL DISPOSITION',
 'ANNUAL SEQUENCE NUMBER',
 'PRIMARY SAMPLING UNIT',
 'CORRECT TELEPHONE NUMBER?',
 'PRIVATE RESIDENCE?',
 'DO YOU LIVE IN COLLEGE HOUSING?',
 'RESIDENT OF STATE',
 'CELLULAR TELEPHONE',
 'ARE YOU 18 YEARS OF AGE OR OLDER?',
 'ARE YOU MALE OR FEMALE?',
 'NUMBER OF ADULTS IN HOUSEHOLD',
 'ARE YOU MALE OR FEMALE?',
 'NUMBER OF ADULT MEN IN HOUSEHOLD',
 'NUMBER OF ADULT WOMEN IN HOUSEHOLD',
 'RESPONDENT SELECTION',
 'SAFE TIME TO TALK?',
 'CORRECT PHONE NUMBER?',
 'IS THIS A CELL PHONE?',
 'ARE YOU 18 YEARS OF AGE OR OLDER?',
 'ARE YOU MALE OR FEMALE?',
 'DO YOU LIVE IN A PRIVATE RESIDENCE?',
 'DO YOU LIVE IN COLLEGE HOUSING?',
 'DO YOU CURRENTLY LIVE IN  ____(STATE)___',
 'DO YOU ALSO HAVE A LANDLINE TELEPHONE?',
 'NUMBER OF ADULTS IN HOUSEHOLD',
 'SEX OF RESPONDENT',
 'GENERAL HEALTH',
 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD',
 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD',
 'POOR PHYSICAL OR MENTAL HEALTH',
 'WHAT IS PRIMARY SOURCE OF HEALTH INSURAN',
 'HAVE PERSONAL HEALTH CARE PROVIDER?',
 'COULD NOT AFFORD TO SEE DOCTOR',
 'LENGTH OF TIME SINCE LAST ROUTINE CHECKU',
 'EXERCISE IN PAST 30 DAYS',
 'HOW MUCH TIME DO YOU SLEEP',
 'LAST VISITED DENTIST OR DENTAL CLINIC',
 'NUMBER OF PERMANENT TEETH REMOVED',
 'EVER DIAGNOSED WITH HEART ATTACK',
 'EVER DIAGNOSED WITH ANGINA OR CORONARY H',
 'EVER DIAGNOSED WITH A STROKE',
 'EVER TOLD HAD ASTHMA',
 'STILL HAVE ASTHMA',
 '(EVER TOLD) (YOU HAD) SKIN CANCER THAT I',
 '(EVER TOLD) (YOU HAD) MELANOMA OR ANY OT',
 'EVER TOLD YOU HAD C.O.P.D. EMPHYSEMA OR',
 '(EVER TOLD) YOU HAD A DEPRESSIVE DISORDE',
 'EVER TOLD YOU HAVE KIDNEY DISEASE?',
 'TOLD HAVE ARTHRITIS',
 '(EVER TOLD) YOU HAD DIABETES',
 'AGE WHEN FIRST TOLD YOU HAD DIABETES',
 'MARITAL STATUS',
 'EDUCATION LEVEL',
 'OWN OR RENT HOME',
 'HOUSEHOLD LANDLINE TELEPHONES',
 'RESIDENTIAL LANDLINE PHONES',
 'DO YOU HAVE A CELL PHONE FOR YOUR PERSON',
 'ARE YOU A VETERAN',
 'EMPLOYMENT STATUS',
 'NUMBER OF CHILDREN IN HOUSEHOLD',
 'INCOME LEVEL',
 'PREGNANCY STATUS',
 'REPORTED WEIGHT IN POUNDS',
 'REPORTED HEIGHT IN FEET AND INCHES',
 'ARE YOU DEAF OR DO YOU HAVE SERIOUS DIFF',
 'BLIND OR DIFFICULTY SEEING',
 'DIFFICULTY CONCENTRATING OR REMEMBERING',
 'DIFFICULTY WALKING OR CLIMBING STAIRS',
 'DIFFICULTY DRESSING OR BATHING',
 'DIFFICULTY DOING ERRANDS ALONE',
 'HAVE YOU EVER HAD A MAMMOGRAM',
 'HOW LONG SINCE LAST MAMMOGRAM',
 'HAVE YOU EVER HAD A CERVICAL CANCER SCRE',
 'TIME SINCE LAST CERVICAL CANCER SCREENIN',
 'HAVE A PAP TEST AND RECENT CERVICAL CANC',
 'HAVE AN H.P.V. TEST AND RECENT CERVICAL',
 'HAD HYSTERECTOMY',
 'EVER HAD SIGMOIDOSCOPY/COLONOSCOPY',
 'EVER HAD A COLONOSCOPY, SIGMOIDOSCOPY, O',
 'HOW LONG HAS IT BEEN SINCE YOU HAD COLON',
 'HOW LONG HAS IT BEEN SINCE YOU HAD SIGMO',
 'TIME SINCE LAST SIGMOIDOSCOPY/COLONOSCOP',
 'EVER HAD ANY OTHER KIND OF TEST FOR COLO',
 'HAVE YOU EVER HAD A VIRTUAL COLONOSCOPY?',
 'HOW LONG HAS IT BEEN SINCE YOU HAD VIRTU',
 'EVER HAD STOOL TEST?',
 'HOW LONG SINCE YOU HAD STOOL TEST?',
 'EVER HAD STOOL DNA TEST?',
 'WAS TEST PART OF COLOGUARD TEST?',
 'HOW LONG SINCE YOU HAD STOOL DNA?',
 'SMOKED AT LEAST 100 CIGARETTES',
 'FREQUENCY OF DAYS NOW SMOKING',
 'USE OF SMOKELESS TOBACCO PRODUCTS',
 'DO YOU NOW USE E-CIGARETTES, OR VAPING P',
 'HOW OLD WHEN YOU FIRST STARTED SMOKING?',
 'HOW OLD WHEN YOU LAST SMOKED?',
 'ON AVERAGE, HOW MANY CIGARETTES DO YOU S',
 'DID YOU HAVE A CT OR CAT SCAN?',
 'WERE ANY CT OR CAT SCANS DONE TO CHECK F',
 'WHEN DID YOU HAVE YOUR MOST RECENT CT OR',
 'DAYS IN PAST 30 HAD ALCOHOLIC BEVERAGE',
 'AVG ALCOHOLIC DRINKS PER DAY IN PAST 30',
 'BINGE DRINKING',
 'MOST DRINKS ON SINGLE OCCASION PAST 30 D',
 'ADULT FLU SHOT/SPRAY PAST 12 MOS',
 'WHEN RECEIVED MOST RECENT SEASONAL FLU S',
 'PNEUMONIA SHOT EVER',
 'RECEIVED TETANUS SHOT SINCE 2005?',
 'EVER TESTED H.I.V.',
 'MONTH AND YEAR OF LAST HIV TEST',
 'DO ANY HIGH RISK SITUATIONS APPLY',
 'HAVE YOU EVER BEEN TOLD YOU TESTED POSIT',
 'HAVE AN 3 MONTH OR LONGER COVID SYMPTOMS',
 'WHICH WAS THE PRIMARY SYMPTOM THAT YOU E',
 'WHEN WAS YOUR LAST BLOOD TEST FOR HIGH B',
 'EVER BEEN TOLD YOU HAVE PRE-DIABETES OR',
 'WHAT TYPE OF DIABETES DO YOU HAVE?',
 'NOW TAKING INSULIN',
 'TIMES CHECKED FOR GLYCOSYLATED HEMOGLOBI',
 'LAST EYE EXAM WHERE PUPILS WERE DILATED',
 'WHEN WAS THE LAST TIME A THEY TOOK A PHO',
 'WHEN WAS THE LAST TIME YOU TOOK A COURSE',
 'EVER HAD FEET SORES OR IRRITATIONS LASTI',
 'TOLD HAD CHRONIC FATIGUE SYNDROME OR MYA',
 'STILL HAVE CHRONIC FATIGUE SYNDROME OR M',
 'HOW MANY HOURS A WEEK ARE YOU BEEN ABLE',
 'WHERE DID YOU GET YOUR LAST FLU SHOT/VAC',
 'EVER HAD AN H.P.V. VACCINATION?',
 'NUMBER OF HPV SHOTS RECEIVED',
 'HAVE YOU EVER HAD THE SHINGLES OR ZOSTER',
 'RECEIVED AT LEAST ONE COVID-19 VACCINATI',
 'GOING TO GET VACCINATED',
 'NUMBER OF COVID-19 VACCINATIONS RECEIVED',
 'INTEND TO GET COVID-19 VACCINATION',
 'MONTH/YEAR OF FIRST COVID-19 VACCINATION',
 'MONTH/YEAR OF SECOND COVID-19 VACCINATIO',
 'DID YOU HAVE A COUGH?',
 'DID YOU COUGH UP PHLEGM?',
 'DID YOU HAVE SHORTNESS OF BREATH?',
 'HAVE YOU EVER BEEN GIVEN A BREATHING TES',
 'HOW MANY YEARS HAVE YOU SMOKED TOBACCO P',
 'HOW MANY TYPES OF CANCER?',
 'AGE TOLD HAD CANCER',
 'TYPE OF CANCER',
 'CURRENTLY RECEIVING TREATMENT FOR CANCER',
 'WHAT TYPE OF DOCTOR PROVIDES MAJORITY OF',
 'DID YOU RECEIVE A SUMMARY OF CANCER TREA',
 'EVER RECEIVE INSTRUCTIONS FROM A DOCTOR',
 'INSTRUCTIONS WRITTEN OR PRINTED',
 'DID HEALTH INSURANCE PAY FOR ALL OF YOUR',
 'EVER DENIED INSURANCE COVERAGE BECAUSE O',
 'PARTICIPATE IN CLINICAL TRIAL AS PART OF',
 'CURRENTLY HAVE PHYSICAL PAIN FROM CANCER',
 'IS PAIN UNDER CONTROL?',
 'EVER HAD PSA TEST',
 'TIME SINCE MOST RECENT PSA TEST',
 'WHAT WAS THE MAIN REASON YOU HAD THIS PS',
 'WHO FIRST SUGGESTED THIS PSA TEST?',
 'DID YOU TALK ABOUT THE ADVANTAGES OR DIS',
 'HAVE YOU EXPERIENCED CONFUSION OR MEMORY',
 'GIVEN UP DAY-TO-DAY CHORES DUE TO CONFUS',
 'NEED ASSISTANCE WITH DAY-TO_DAY ACTIVITI',
 'WHEN YOU NEED HELP WITH DAY-TO-DAY ACTIV',
 'DOES CONFUSION OR MEMORY LOSS INTERFERE',
 'HAVE YOU DISCUSSED YOUR CONFUSION OR MEM',
 'PROVIDED REGULAR CARE FOR FAMILY OR FRIE',
 'RELATIONSHIP OF PERSON TO WHOM YOU ARE G',
 'HOW LONG PROVIDED CARE FOR PERSON.',
 'HOW MANY HOURS DO YOU PROVIDE CARE FOR P',
 'WHAT IS THE MAJOR HEALTH PROBLEM, ILLNES',
 'DOES PERSON BEING CARED FOR HAVE ALZHEIM',
 'MANAGED PERSONAL CARE',
 'MANAGED HOUSEHOLD TASKS',
 'DO YOU EXPECT TO HAVE A RELATIVE YOU WIL',
 'LIVE WITH ANYONE DEPRESSED, MENTALLY ILL',
 'LIVE WITH A PROBLEM DRINKER/ALCOHOLIC?',
 'LIVE WITH ANYONE WHO USED ILLEGAL DRUGS',
 'LIVE WITH ANYONE WHO SERVED TIME IN PRIS',
 'WERE YOUR PARENTS DIVORCED/SEPERATED?',
 'HOW OFTEN DID YOUR PARENTS BEAT EACH OTH',
 'HOW OFTEN DID A PARENT PHYSICALLY HURT Y',
 'HOW OFTEN DID A PARENT SWEAR AT YOU?',
 'HOW OFTEN DID ANYONE EVER TOUCH YOU SEXU',
 'HOW OFTEN DID ANYONE MAKE YOU TOUCH THEM',
 'HOW OFTEN DID ANYONE EVER FORCE YOU TO H',
 'DID AN ADULT MAKE YOU FEEL SAFE AND PROT',
 'DID AN ADULT MAKE SURE BASIC NEEDS WERE',
 'SATISFACTION WITH LIFE',
 'HOW OFTEN GET EMOTIONAL SUPPORT NEEDED',
 'HOW OFTEN DO YOU FEEL SOCIALLY ISOLATED',
 'HAVE YOU LOST EMPLOYMENT OR HAD HOURS RE',
 'DURING THE PAST 12 MONTHS HAVE YOU RECEI',
 'HOW OFTEN DID THE FOOD THAT YOU BOUGHT N',
 'WERE YOU NOT ABLE TO PAY YOUR BILLS?',
 'WERE YOU NOT ABLE TO PAY UTILITY BILLS O',
 'HAS A LACK OF RELIABLE TRANSPORTATION KE',
 'HOW OFTEN HAVE YOU FELT THIS KIND OF STR',
 'DURING THE PAST 30 DAYS, ON HOW MANY DAY',
 'DID YOU SMOKE MARIJUANA OR CANNABIS?',
 'DID YOU EAT MARIJUANA OR CANNABIS?',
 'DID YOU VAPE MARIJUANA OR CANNABIS?',
 'DID YOU DAB MARIJUANA OR CANNABIS?',
 'DID YOU USE MARIJUANA OR CANNABIS SOME O',
 'DURING THE PAST 30 DAYS, HOW DID YOU PRI',
 'INTERVAL SINCE LAST SMOKED',
 'STOPPED SMOKING IN PAST 12 MONTHS',
 'DO YOU USUALLY SMOKE MENTHOL CIGARETTES?',
 'DO YOU USUALLY USE MENTHOL E-CIGARETTES?',
 'HAVE YOU HEARD OF HEATED TOBACCO PRODUCT',
 'ASKED DURING CHECKUP IF YOU DRINK ALCHOH',
 'ASKED IN PERSON OR BY FORM HOW MUCH YOU',
 'ASKED WHETHER YOU DRANK [5 FOR MEN /4 FO',
 'OFFERED ADVICE ABOUT WHAT LEVEL OF DRINK',
 'WERE YOU ADVISED TO REDUCE OR QUIT YOUR',
 'ANY FIREARMS IN HOME',
 'ANY FIREARMS LOADED',
 'ANY LOADED FIREARMS ALSO UNLOCKED',
 'SEX OF CHILD',
 'CHILD´S SEX AT BIRT',
 'RELATIONSHIP TO CHILD',
 'HLTH PRO EVER SAID CHILD HAS ASTHMA',
 'CHILD STILL HAVE ASTHMA?',
 'ARE YOU MALE OR FEMALE?',
 'SEXUAL ORIENTATION',
 'SEXUAL ORIENTATION',
 'DO YOU CONSIDER YOURSELF TO BE TRANSGEND',
 'HAVE YOU HAVE SEXUAL INTERCOURSE?',
 'DID YOU DO ANYTHING TO KEEP FROM GETTING',
 'WHAT DID YOU DO TO KEEP YOU FROM GETTING',
 'ARE YOU DOING ANYTHING TO KEEP FROM GETT',
 'WHERE DID YOU GET WHAT YOU USED TO PREVE',
 'WHAT WAS MAIN REASON FOR NOT DOING ANYTH',
 'WHAT IS YOUR PREFERRED BIRTH CONTROL MET',
 'HOW DO OTHER PEOPLE USUALLY CLASSIFY YOU',
 'HOW OFTEN DO YOU THINK ABOUT YOUR RACE?',
 'WERE YOU TREATED WORSE THAN, THE SAME, O',
 'HOW DO YOU FEEL YOU WERE TREATED AT WORK',
 'WHEN SEEKING HEALTH CARE PAST 12 MONTHS,',
 'TIMES PAST 30 DAYS FELT PHYSICAL SYMPTOM',
 'QUESTIONNAIRE VERSION IDENTIFIER',
 'LANGUAGE IDENTIFIER',
 'METROPOLITAN STATUS',
 'URBAN/RURAL STATUS',
 'METROPOLITAN STATUS CODE',
 'SAMPLE DESIGN STRATIFICATION VARIABLE',
 'STRATUM WEIGHT',
 'RAW WEIGHTING FACTOR USED IN RAKING',
 'DESIGN WEIGHT USED IN RAKING',
 'IMPUTED RACE/ETHNICITY VALUE',
 'CHILD HISPANIC, LATINO/A, OR SPANISH ORI',
 'CHILD NON-HISPANIC RACE INCLUDING MULTIR',
 'PREFERRED CHILD RACE CATEGORIES',
 'FOUR LEVEL CHILD AGE',
 'FINAL CHILD WEIGHT: LAND-LINE AND CELL-P',
 'DUAL PHONE USE CATEGORIES',
 'DUAL PHONE USE CORRECTION FACTOR',
 'TRUNCATED DESIGN WEIGHT USED IN ADULT CO',
 'FINAL WEIGHT: LAND-LINE AND CELL-PHONE D',
 'ADULTS WITH GOOD OR BETTER HEALTH',
 'COMPUTED PHYSICAL HEALTH STATUS',
 'COMPUTED MENTAL HEALTH STATUS',
 'HAVE ANY HEALTH INSURANCE',
 'RESPONDENTS AGED 18-64 WITH HEALTH INSUR',
 'LEISURE TIME PHYSICAL ACTIVITY CALCULATE',
 'RISK FACTOR FOR HAVING HAD PERMANENT TEE',
 'ADULTS AGED 65+ WHO HAVE HAD ALL THEIR N',
 'ADULTS WHO HAVE VISITED A DENTIST, DENTA',
 'RESPONDENTS THAT HAVE EVER REPORTED HAVI',
 'LIFETIME ASTHMA CALCULATED VARIABLE',
 'CURRENT ASTHMA CALCULATED VARIABLE',
 'COMPUTED ASTHMA STATUS',
 'RESPONDENTS DIAGNOSED WITH ARTHRITIS',
 'COMPUTED PREFERRED RACE',
 'CALCULATED NON-HISPANIC RACE INCLUDING M',
 'HISPANIC, LATINO/A, OR SPANISH ORIGIN CA',
 'COMPUTED RACE-ETHNICITY GROUPING',
 'COMPUTED NON-HISPANIC WHITES/ALL OTHERS',
 'COMPUTED FIVE LEVEL RACE/ETHNICITY CATEG',
 'COMPUTED RACE GROUPS USED FOR INTERNET P',
 'CALCULATED SEX VARIABLE',
 'REPORTED AGE IN FIVE-YEAR AGE CATEGORIES',
 'REPORTED AGE IN TWO AGE GROUPS CALCULATE',
 'IMPUTED AGE VALUE COLLAPSED ABOVE 80',
 'IMPUTED AGE IN SIX GROUPS',
 'COMPUTED HEIGHT IN INCHES',
 'COMPUTED HEIGHT IN METERS',
 'COMPUTED WEIGHT IN KILOGRAMS',
 'COMPUTED BODY MASS INDEX',
 'COMPUTED BODY MASS INDEX CATEGORIES',
 'OVERWEIGHT OR OBESE CALCULATED VARIABLE',
 'COMPUTED NUMBER OF CHILDREN IN HOUSEHOLD',
 'COMPUTED LEVEL OF EDUCATION COMPLETED CA',
 'COMPUTED INCOME CATEGORIES',
 'WOMEN RESPONDENTS AGED 40+ WHO HAVE HAD',
 'WOMEN RESPONDENTS AGED 50-74 WHO HAVE HA',
 'HAD COLONOSCOPY CALCULATED VARIABLE',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A CO',
 'HAD SIGMOIDOSCOPY CALCULATED VARIABLE',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A SI',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A SI',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A ST',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A ST',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A VI',
 'RESPONDENTS AGED 45-75 WHO HAVE HAD A SI',
 'RESPONDENTS AGED 45-75 WHO HAVE FULLY ME',
 'COMPUTED SMOKING STATUS',
 'CURRENT SMOKING CALCULATED VARIABLE',
 'CURRENT E-CIGARETTE USER CALCULATED VARI',
 'NUMBER OF YEARS SMOKED CIGARETTES',
 'NUMBER OF PACKS OF CIGARETTES SMOKED PER',
 'YEARS SMOKED REPORTED PACKS PER DAY',
 'NUMBER OF YEARS SINCE QUIT SMOKING CIGAR',
 'SMOKING GROUP',
 'LUNG CANCER SCREENING RECOMMENDATION STA',
 'DRINK ANY ALCOHOLIC BEVERAGES IN PAST 30',
 'COMPUTED DRINK-OCCASIONS-PER-DAY',
 'BINGE DRINKING CALCULATED VARIABLE',
 'COMPUTED NUMBER OF DRINKS OF ALCOHOL BEV',
 'HEAVY ALCOHOL CONSUMPTION  CALCULATED VA',
 'FLU SHOT CALCULATED VARIABLE',
 'PNEUMONIA VACCINATION CALCULATED VARIABL',
 'EVER BEEN TESTED FOR HIV CALCULATED VARI']

# Kaggle Dataset: Indicators of Heart Disease (2022)

https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease/data

In [8]:
# Download latest version
path = kagglehub.dataset_download('kamilpytlak/personal-key-indicators-of-heart-disease')

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Lander\.cache\kagglehub\datasets\kamilpytlak\personal-key-indicators-of-heart-disease\versions\6

In [ ]:
data_path = '../data/raw/heart_disease/2020/heart_2020_cleaned.csv'
df_heart_2020 = pd.read_csv(data_path)

display(df_heart_2020.head())
print(df_heart_2020['HeartDisease'].value_counts(), end='\n\n')
ds.get_cardinality(df_heart_2020)

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

HeartDisease
No     292422
Yes     27373
Name: count, dtype: int64

pandas.DataFrame shape: (319795, 18)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
HeartDisease,2,0.000625,0,0.0,object,Binary
BMI,3604,1.126972,0,0.0,float64,Numeric - Discrete
Smoking,2,0.000625,0,0.0,object,Binary
AlcoholDrinking,2,0.000625,0,0.0,object,Binary
Stroke,2,0.000625,0,0.0,object,Binary
PhysicalHealth,31,0.009694,0,0.0,float64,Numeric - Discrete
MentalHealth,31,0.009694,0,0.0,float64,Numeric - Discrete
DiffWalking,2,0.000625,0,0.0,object,Binary
Sex,2,0.000625,0,0.0,object,Binary
AgeCategory,13,0.004065,0,0.0,object,Numeric - Discrete
Race,6,0.001876,0,0.0,object,Categoric
Diabetic,4,0.001251,0,0.0,object,Categoric
PhysicalActivity,2,0.000625,0,0.0,object,Binary
GenHealth,5,0.001564,0,0.0,object,Categoric
SleepTime,24,0.007505,0,0.0,float64,Numeric - Discrete
Asthma,2,0.000625,0,0.0,object,Binary
KidneyDisease,2,0.000625,0,0.0,object,Binary
SkinCancer,2,0.000625,0,0.0,object,Binary

In [ ]:
data_path = '../data/raw/heart_disease/2022/heart_2022_no_nans.csv'
df_heart_2022_clean = pd.read_csv(data_path)

display(df_heart_2022_clean.head())
print(df_heart_2022_clean['HadHeartAttack'].value_counts(), end='\n\n')
ds.get_cardinality(df_heart_2022_clean)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

HadHeartAttack
No     232587
Yes     13435
Name: count, dtype: int64

pandas.DataFrame shape: (246022, 40)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
State,54,0.021949,0,0.0,object,Numeric - Discrete
Sex,2,0.000813,0,0.0,object,Binary
GeneralHealth,5,0.002032,0,0.0,object,Categoric
PhysicalHealthDays,31,0.0126,0,0.0,float64,Numeric - Discrete
MentalHealthDays,31,0.0126,0,0.0,float64,Numeric - Discrete
LastCheckupTime,4,0.001626,0,0.0,object,Categoric
PhysicalActivities,2,0.000813,0,0.0,object,Binary
SleepHours,23,0.009349,0,0.0,float64,Numeric - Discrete
RemovedTeeth,4,0.001626,0,0.0,object,Categoric
HadHeartAttack,2,0.000813,0,0.0,object,Binary
HadAngina,2,0.000813,0,0.0,object,Binary
HadStroke,2,0.000813,0,0.0,object,Binary
HadAsthma,2,0.000813,0,0.0,object,Binary
HadSkinCancer,2,0.000813,0,0.0,object,Binary
HadCOPD,2,0.000813,0,0.0,object,Binary
HadDepressiveDisorder,2,0.000813,0,0.0,object,Binary
HadKidneyDisease,2,0.000813,0,0.0,object,Binary
HadArthritis,2,0.000813,0,0.0,object,Binary
HadDiabetes,4,0.001626,0,0.0,object,Categoric
DeafOrHardOfHearing,2,0.000813,0,0.0,object,Binary
BlindOrVisionDifficulty,2,0.000813,0,0.0,object,Binary
DifficultyConcentrating,2,0.000813,0,0.0,object,Binary
DifficultyWalking,2,0.000813,0,0.0,object,Binary
DifficultyDressingBathing,2,0.000813,0,0.0,object,Binary
DifficultyErrands,2,0.000813,0,0.0,object,Binary
SmokerStatus,4,0.001626,0,0.0,object,Categoric
ECigaretteUsage,4,0.001626,0,0.0,object,Categoric
ChestScan,2,0.000813,0,0.0,object,Binary
RaceEthnicityCategory,5,0.002032,0,0.0,object,Categoric
AgeCategory,13,0.005284,0,0.0,object,Numeric - Discrete
HeightInMeters,101,0.041053,0,0.0,float64,Numeric - Discrete
WeightInKilograms,516,0.209737,0,0.0,float64,Numeric - Discrete
BMI,3514,1.428328,0,0.0,float64,Numeric - Discrete
AlcoholDrinkers,2,0.000813,0,0.0,object,Binary
HIVTesting,2,0.000813,0,0.0,object,Binary
FluVaxLast12,2,0.000813,0,0.0,object,Binary
PneumoVaxEver,2,0.000813,0,0.0,object,Binary
TetanusLast10Tdap,4,0.001626,0,0.0,object,Categoric
HighRiskLastYear,2,0.000813,0,0.0,object,Binary
CovidPos,3,0.001219,0,0.0,object,Categoric

# Heart Disease

Janosi, A., Steinbrunn, W., Pfisterer, M., & Detrano, R. (1989). Heart Disease (Dataset). [UCI Machine Learning Repository](https://doi.org/10.24432/C52P4X).

In [12]:
# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
  
# data (as pandas dataframes) 
X = heart_disease.data.features 
y = heart_disease.data.targets 
  
print(heart_disease.metadata) 
display(X.head())
display(heart_disease.variables) 
ds.get_cardinality(X)

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sandhu, K. Guppy, S. Lee, V. Froelicher', 'venue': 'American Journal of Cardiology', 'year': 1989, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/a7d714f8f87bfc41351eb5ae1e5472f0ebbe0574', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '2756873', 'pmcid': None}, 'additional_info': {'summary': 'This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them.  In particular, the Cleveland database is the only one that has been used by ML researchers to date.  The "goal" field refers to the presence of heart disease in the patient.  It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).  \n   \nThe names and social security numbers of the patients were recently removed from the database, replaced with dummy values.\n\nOne file has been "processed", that one containing the Cleveland database.  All four unprocessed files also exist in this directory.\n\nTo see Test Costs (donated by Peter Turney), please see the folder "Costs" ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Only 14 attributes used:\r\n      1. #3  (age)       \r\n      2. #4  (sex)       \r\n      3. #9  (cp)        \r\n      4. #10 (trestbps)  \r\n      5. #12 (chol)      \r\n      6. #16 (fbs)       \r\n      7. #19 (restecg)   \r\n      8. #32 (thalach)   \r\n      9. #38 (exang)     \r\n      10. #40 (oldpeak)   \r\n      11. #41 (slope)     \r\n      12. #44 (ca)        \r\n      13. #51 (thal)      \r\n      14. #58 (num)       (the predicted attribute)\r\n\r\nComplete attribute documentation:\r\n      1 id: patient identification number\r\n      2 ccf: social security number (I replaced this with a dummy value of 0)\r\n      3 age: age in years\r\n      4 sex: sex (1 = male; 0 = female)\r\n      5 painloc: chest pain location (1 = substernal; 0 = otherwise)\r\n      6 painexer (1 = provoked by exertion; 0 = otherwise)\r\n      7 relrest (1 = relieved after rest; 0 = otherwise)\r\n      8 pncaden (sum of 5, 6, and 7)\r\n      9 cp: chest pain type\r\n        -- Value 1: typical angina\r\n        -- Value 2: atypical angina\r\n        -- Value 3: non-anginal pain\r\n        -- Value 4: asymptomatic\r\n     10 trestbps: resting blood pressure (in mm Hg on admission to the hospital)\r\n     11 htn\r\n     12 chol: serum cholestoral in mg/dl\r\n     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)\r\n     14 cigs (cigarettes per day)\r\n     15 years (number of years as a smoker)\r\n     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)\r\n     17 dm (1 = history of diabetes; 0 = no such history)\r\n     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)\r\n     19 restecg: resting electrocardiographic results\r\n        -- Value 0: normal\r\n        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)\r\n        -- Value 2: showing probable or definite left ventricular hypertrophy by Estes\' criteria\r\n     20 ekgmo (month of exercise ECG reading)\r\n     21 ekgday(day of exercise ECG reading)\r\n     22 ekgyr (year of exercise ECG reading)\r\n     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)\r\n     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)\r\n     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)\r\n     28 proto: exercise protocol\r\n          1 = Bruce     \r\n          2 = Kottus\r\n          3 = McHenry\r\n          4 = fast Balke\r\n          5 = Balke\r\n          6 = Noughton \r\n          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was written!)\r\n          8 = bike 125 kpa min/min  \r\n          9 = bike 100 kpa min/min\r\n         10 = bike 75 kpa min/min\r\n         11 = bike 50 kpa min/min\r\n         12 = arm ergometer\r\n     29 thaldur: duration of exercise test in minutes\r\n     30 thaltime: time when ST measure depression was noted\r\n     31 met: mets achieved\r\n     32 thalach: maximum heart rate achieved\r\n     33 thalrest: resting heart rate\r\n     34 tpeakbps: peak exercise blood pressure (first of 2 parts)\r\n     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)\r\n     36 dummy\r\n     37 trestbpd: resting blood pressure\r\n     38 exang: exercise induced angina (1 = yes; 0 = no)\r\n     39 xhypo: (1 = yes; 0 = no)\r\n     40 oldpeak = ST depression induced by exercise relative to rest\r\n     41 slope: the slope of the peak exercise ST segment\r\n        -- Value 1: upsloping\r\n        -- Value 2: flat\r\n        -- Value 3: downsloping\r\n     42 rldv5: height at rest\r\n     43 rldv5e: height at peak exercise\r\n     44 ca: number of major vessels (0-3) colored by flourosopy\r\n     45 restckm: irrelevant\r\n     46 exerckm: irrelevant\r\n     47 restef: rest raidonuclid (sp?) ejection fraction\r\n     48 restwm: rest wall (sp?) motion abnormality\r\n        0 = none\r\n        1 = mild or moderate\r\n        2 = moderate or severe\r\n        3 = akinesis or dyskmem (sp?)\r\n     49 exeref: exercise radinalid (sp?) ejection fraction\r\n     50 exerwm: exercise wall (sp?) motion \r\n     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect\r\n     52 thalsev: not used\r\n     53 thalpul: not used\r\n     54 earlobe: not used\r\n     55 cmo: month of cardiac cath (sp?)  (perhaps "call")\r\n     56 cday: day of cardiac cath (sp?)\r\n     57 cyr: year of cardiac cath (sp?)\r\n     58 num: diagnosis of heart disease (angiographic disease status)\r\n        -- Value 0: < 50% diameter narrowing\r\n        -- Value 1: > 50% diameter narrowing\r\n        (in any major vessel: attributes 59 through 68 are vessels)\r\n     59 lmt\r\n     60 ladprox\r\n     61 laddist\r\n     62 diag\r\n     63 cxmain\r\n     64 ramus\r\n     65 om1\r\n     66 om2\r\n     67 rcaprox\r\n     68 rcadist\r\n     69 lvx1: not used\r\n     70 lvx2: not used\r\n     71 lvx3: not used\r\n     72 lvx4: not used\r\n     73 lvf: not used\r\n     74 cathef: not used\r\n     75 junk: not used\r\n     76 name: last name of patient  (I replaced this with the dummy string "name")', 'citation': None}}

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0

,name,role,type,demographic,description,units,missing_values
0,age,Feature,Integer,Age,None,years,no
1,sex,Feature,Categorical,Sex,None,None,no
2,cp,Feature,Categorical,None,None,None,no
3,trestbps,Feature,Integer,None,resting blood pressure (on admission to the ho...,mm Hg,no
4,chol,Feature,Integer,None,serum cholestoral,mg/dl,no
5,fbs,Feature,Categorical,None,fasting blood sugar > 120 mg/dl,None,no
6,restecg,Feature,Categorical,None,None,None,no
7,thalach,Feature,Integer,None,maximum heart rate achieved,None,no
8,exang,Feature,Categorical,None,exercise induced angina,None,no
9,oldpeak,Feature,Integer,None,ST depression induced by exercise relative to ...,None,no
10,slope,Feature,Categorical,None,None,None,no
11,ca,Feature,Integer,None,number of major vessels (0-3) colored by flour...,None,yes
12,thal,Feature,Categorical,None,None,None,yes
13,num,Target,Integer,None,diagnosis of heart disease,None,no

pandas.DataFrame shape: (303, 13)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
age,41,13.531353,0,0.0,int64,Numeric - Discrete
sex,2,0.660066,0,0.0,int64,Binary
cp,4,1.320132,0,0.0,int64,Categoric
trestbps,50,16.50165,0,0.0,int64,Numeric - Discrete
chol,152,50.165017,0,0.0,int64,Numeric - Continuous
fbs,2,0.660066,0,0.0,int64,Binary
restecg,3,0.990099,0,0.0,int64,Categoric
thalach,91,30.033003,0,0.0,int64,Numeric - Continuous
exang,2,0.660066,0,0.0,int64,Binary
oldpeak,40,13.20132,0,0.0,float64,Numeric - Discrete
slope,3,0.990099,0,0.0,int64,Categoric
ca,4,1.320132,4,1.320132,float64,Categoric
thal,3,0.990099,2,0.660066,float64,Categoric

# CDC Diabetes Health Indicators

https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators

In [13]:
# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
  
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features 
y = cdc_diabetes_health_indicators.data.targets 

pd.options.display.max_colwidth = None
print(cdc_diabetes_health_indicators.metadata) 
display(X.head())
display(cdc_diabetes_health_indicators.variables) 
ds.get_cardinality(X)

{'uci_id': 891, 'name': 'CDC Diabetes Health Indicators', 'repository_url': 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators', 'data_url': 'https://archive.ics.uci.edu/static/public/891/data.csv', 'abstract': 'The Diabetes Health Indicators Dataset contains healthcare statistics and lifestyle survey information about people in general along with their diagnosis of diabetes. The 35 features consist of some demographics, lab test results, and answers to survey questions for each patient. The target variable for classification is whether a patient has diabetes, is pre-diabetic, or healthy. ', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Multivariate'], 'num_instances': 253680, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Sex', 'Age', 'Education Level', 'Income'], 'target_col': ['Diabetes_binary'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2017, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C53919', 'creators': [], 'intro_paper': {'ID': 308, 'type': 'NATIVE', 'title': 'Incidence of End-Stage Renal Disease Attributed to Diabetes Among Persons with Diagnosed Diabetes — United States and Puerto Rico, 2000–2014', 'authors': 'Nilka Rios Burrows, MPH; Israel Hora, PhD; Linda S. Geiss, MA; Edward W. Gregg, PhD; Ann Albright, PhD', 'venue': 'Morbidity and Mortality Weekly Report', 'year': 2017, 'journal': None, 'DOI': None, 'URL': 'https://www.cdc.gov/mmwr/volumes/66/wr/mm6643a2.htm', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Dataset link: https://www.cdc.gov/brfss/annual_data/annual_2014.html', 'purpose': 'To better understand the relationship between  lifestyle and diabetes in the US', 'funded_by': 'The CDC', 'instances_represent': 'Each row represents a person participating in this study.', 'recommended_data_splits': 'Cross validation or a fixed train-test split could be used.', 'sensitive_data': '- Gender\n- Income\n- Education level', 'preprocessing_description': 'Bucketing of age', 'variable_info': '- Diabetes diagnosis\n- Demographics (race, sex)\n- Personal information (income, educations)\n- Health history (drinking, smoking, mental health, physical health)', 'citation': None}, 'external_url': 'https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset'}

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4

,name,role,type,demographic,description,units,missing_values
0,ID,ID,Integer,None,Patient ID,None,no
1,Diabetes_binary,Target,Binary,None,0 = no diabetes 1 = prediabetes or diabetes,None,no
2,HighBP,Feature,Binary,None,0 = no high BP 1 = high BP,None,no
3,HighChol,Feature,Binary,None,0 = no high cholesterol 1 = high cholesterol,None,no
4,CholCheck,Feature,Binary,None,0 = no cholesterol check in 5 years 1 = yes cholesterol check in 5 years,None,no
5,BMI,Feature,Integer,None,Body Mass Index,None,no
6,Smoker,Feature,Binary,None,Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes] 0 = no 1 = yes,None,no
7,Stroke,Feature,Binary,None,(Ever told) you had a stroke. 0 = no 1 = yes,None,no
8,HeartDiseaseorAttack,Feature,Binary,None,coronary heart disease (CHD) or myocardial infarction (MI) 0 = no 1 = yes,None,no
9,PhysActivity,Feature,Binary,None,physical activity in past 30 days - not including job 0 = no 1 = yes,None,no
10,Fruits,Feature,Binary,None,Consume Fruit 1 or more times per day 0 = no 1 = yes,None,no
11,Veggies,Feature,Binary,None,Consume Vegetables 1 or more times per day 0 = no 1 = yes,None,no
12,HvyAlcoholConsump,Feature,Binary,None,Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) 0 = no 1 = yes,None,no
13,AnyHealthcare,Feature,Binary,None,"Have any kind of health care coverage, including health insurance, prepaid plans such as HMO, etc. 0 = no 1 = yes",None,no
14,NoDocbcCost,Feature,Binary,None,Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? 0 = no 1 = yes,None,no
15,GenHlth,Feature,Integer,None,Would you say that in general your health is: scale 1-5 1 = excellent 2 = very good 3 = good 4 = fair 5 = poor,None,no
16,MentHlth,Feature,Integer,None,"Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good? scale 1-30 days",None,no
17,PhysHlth,Feature,Integer,None,"Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good? scale 1-30 days",None,no
18,DiffWalk,Feature,Binary,None,Do you have serious difficulty walking or climbing stairs? 0 = no 1 = yes,None,no
19,Sex,Feature,Binary,Sex,0 = female 1 = male,None,no
20,Age,Feature,Integer,Age,13-level age category (_AGEG5YR see codebook) 1 = 18-24 9 = 60-64 13 = 80 or older,None,no
21,Education,Feature,Integer,Education Level,Education level (EDUCA see codebook) scale 1-6 1 = Never attended school or only kindergarten 2 = Grades 1 through 8 (Elementary) 3 = Grades 9 through 11 (Some high school) 4 = Grade 12 or GED (High school graduate) 5 = College 1 year to 3 years (Some college or technical school) 6 = College 4 years or more (College graduate),None,no
22,Income,Feature,Integer,Income,"Income scale (INCOME2 see codebook) scale 1-8 1 = less than $10,000 5 = less than $35,000 8 = $75,000 or more",None,no

pandas.DataFrame shape: (253680, 21)

,Card,%_Card,NaN_Values,%_NaN_Values,Type,Class
HighBP,2,0.000788,0,0.0,int64,Binary
HighChol,2,0.000788,0,0.0,int64,Binary
CholCheck,2,0.000788,0,0.0,int64,Binary
BMI,84,0.033113,0,0.0,int64,Numeric - Discrete
Smoker,2,0.000788,0,0.0,int64,Binary
Stroke,2,0.000788,0,0.0,int64,Binary
HeartDiseaseorAttack,2,0.000788,0,0.0,int64,Binary
PhysActivity,2,0.000788,0,0.0,int64,Binary
Fruits,2,0.000788,0,0.0,int64,Binary
Veggies,2,0.000788,0,0.0,int64,Binary
HvyAlcoholConsump,2,0.000788,0,0.0,int64,Binary
AnyHealthcare,2,0.000788,0,0.0,int64,Binary
NoDocbcCost,2,0.000788,0,0.0,int64,Binary
GenHlth,5,0.001971,0,0.0,int64,Categoric
MentHlth,31,0.01222,0,0.0,int64,Numeric - Discrete
PhysHlth,31,0.01222,0,0.0,int64,Numeric - Discrete
DiffWalk,2,0.000788,0,0.0,int64,Binary
Sex,2,0.000788,0,0.0,int64,Binary
Age,13,0.005125,0,0.0,int64,Numeric - Discrete
Education,6,0.002365,0,0.0,int64,Categoric
Income,8,0.003154,0,0.0,int64,Categoric

In [14]:
y.value_counts()

Diabetes_binary
0                  218334
1                   35346
Name: count, dtype: int64

# Myocardial Infarction Complications

Golovenkin, S., Shulman, V., Rossiev, D., Shesternya, P., Nikulina, S., Orlova, Y., & Voino-Yasenetsky, V. (2020). Myocardial infarction complications [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C53P5M.

In [15]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
myocardial_infarction_complications = fetch_ucirepo(id=579) 
  
# data (as pandas dataframes) 
X = myocardial_infarction_complications.data.features 
y = myocardial_infarction_complications.data.targets 
  
print(myocardial_infarction_complications.metadata) 
display(X.head())
display(myocardial_infarction_complications.variables) 
ds.get_cardinality(X)

{'uci_id': 579, 'name': 'Myocardial infarction complications', 'repository_url': 'https://archive.ics.uci.edu/dataset/579/myocardial+infarction+complications', 'data_url': 'https://archive.ics.uci.edu/static/public/579/data.csv', 'abstract': 'Prediction of myocardial infarction complications', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1700, 'num_features': 111, 'feature_types': ['Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['FIBR_PREDS', 'PREDS_TAH', 'JELUD_TAH', 'FIBR_JELUD', 'A_V_BLOK', 'OTEK_LANC', 'RAZRIV', 'DRESSLER', 'ZSN', 'REC_IM', 'P_IM_STEN', 'LET_IS'], 'index_col': ['ID'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2020, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C53P5M', 'creators': ['S.E. Golovenkin', 'V.A. Shulman', 'D.A. Rossiev', 'P.A. Shesternya', 'S.Yu. Nikulina', 'Yu.V. Orlova', 'V.F. Voino-Yasenetsky'], 'intro_paper': {'ID': 228, 'type': 'NATIVE', 'title': 'Trajectories, bifurcations, and pseudo-time in large clinical datasets: applications to myocardial infarction and diabetes data', 'authors': 'S. E. Golovenkin, Jonathan Bac, A. Chervov, E. M. Mirkes, Y. Orlova, E. Barillot, A. Gorban, A. Zinovyev', 'venue': 'GigaScience', 'year': 2020, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/0ea5a469d4f0d83ce6a0d2f7215269877afaf628', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '33241287', 'pmcid': None}, 'additional_info': {'summary': 'Problems of real-life complexity are needed to test and compare various data mining and pattern recognition methods. The proposed database can be used to solve two practically important problems: predicting complications of Myocardial Infarction (MI) based on information about the patient (i) at the time of admission and (ii) on the third day of the hospital period. Another important group of tasks is phenotyping of disease (cluster analysis), dynamic phenotyping (filament extraction and identification of disease trajectories) and visualisation (disease mapping). \r\nMI is one of the most challenging problems of modern medicine. Acute myocardial infarction is associated with high mortality in the first year after it. The incidence of MI remains high in all countries. This is especially true for the urban population of highly developed countries, which is exposed to chronic stress factors, irregular and not always balanced nutrition. In the United States, for example, more than a million people suffer from MI every year, and 200-300 thousand of them die from acute MI before arriving at the hospital. \r\nThe course of the disease in patients with MI is different. MI can occur without complications or with complications that do not worsen the long-term prognosis. At the same time, about half of patients in the acute and subacute periods have complications that lead to worsening of the disease and even death. Even an experienced specialist can not always foresee the development of these complications. In this regard, predicting complications of myocardial infarction in order to timely carry out the necessary preventive measures is an important task. \r\n\r\nProblems to solve\r\nIn general columns 2-112 can be used as input data for prediction. Possible complications (outputs) are listed in columns 113-124.\r\nThere are four possible time moments for complication prediction: on base of the information known at\r\n1.\tthe time of admission to hospital: all input columns (2-112) except 93, 94, 95, 100, 101, 102, 103, 104, 105 can be used for prediction;\r\n2.\tthe end of the first day (24 hours after admission to the hospital): all input columns (2-112) except 94, 95, 101, 102, 104, 105 can be used for prediction;\r\n3.\tthe end of the second day (48 hours after admission to the hospital) all input columns (2-112) except 95, 102, 105 can be used for prediction;\r\n4.\tthe end of the third day (72 hours after admission to the hospital) all input columns (2-112) can be used for prediction.\r\n\r\nYou can find detailed description of database, descriptive statistics and csv version of database in DOI: 10.25392/leicester.data.12045261.v3\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Table of abbreviations\r\nFC is the functional class of angina pectoris in the last year according to Campeau, L., 1976. Grading of angina pectoris. Circulation, 54(3), pp.522-523.\r\nCHD is coronary heart disease.\r\nHF is heart failure.\r\nECG is electrocardiogram.\r\nAV is atrioventricular block.\r\nLBBB is left bundle branch block.\r\nRBBB is right bundle branch block.\r\nQRS is QRS complex in ECG\r\nIU is international unit.\r\nICU is intensive care unit.\r\nESR is erythrocyte sedimentation rate.\r\nNSAID is non-steroidal anti-inflammatory drugs.\r\n\r\nList of attributes\r\n1. Record ID (ID): Unique identifier. Cannot be related to participant. It can be used for reference only.\r\n2. Age (AGE): Real. Age of patient.\r\n3. Gender (SEX): Nominal: \r\n\t\t\tCases\tFraction\r\n0: female\t635\t37.35%\r\n1: male\t1065\t62.65%\r\nMissing\t\t0\t0%\r\n4. Quantity of myocardial infarctions in the anamnesis (INF_ANAM): Ordinal\r\n\t\t\tCases\tFraction\r\n0: zero\t\t1060\t62.35%\r\n1: one\t\t\t410\t24.12%\r\n2: two\t\t\t147\t8.65%\r\n3: three and more\t79\t4.65%\r\nMissing\t\t\t4\t0.24%\r\n5. Exertional angina pectoris in the anamnesis (STENOK_AN): Ordinal\r\n\t\t\t\tCases\tFraction\r\n0: never\t\t\t661\t38.88%\r\n1: during the last year\t146\t8.59%\r\n2: one year ago\t\t137\t8.06%\r\n3: two years ago\t\t117\t6.88%\r\n4: three years ago\t\t76\t4.47%\r\n5: 4-5 years ago\t\t125\t7.35%\r\n6: more than 5 years ago\t332\t19.53%\r\nMissing\t\t\t\t106\t6.24%\r\n6. Functional class (FC) of angina pectoris in the last year (FK_STENOK): Ordinal\r\n\t\t\t\t\tCases\tFraction\r\n0: there is no angina pectoris\t\t661\t38.88%\r\n1: I FC\t\t\t\t47\t2.76%\r\n2: II FC\t\t\t\t854\t50.24%\r\n3: III FC\t\t\t\t54\t3.18%\r\n4: IV FC\t\t\t\t11\t0.65%\r\nMissing\t\t\t\t\t73\t4.29%\r\n7. Coronary heart disease (CHD) in recent weeks, days before admission to hospital (IBS_POST): Ordinal\r\n\t\t\t\t\tCases\tFraction\r\n0: there was no Ð¡HD\t\t\t418\t24.59%\r\n1: exertional angina pectoris\t\t548\t32.24%\r\n2: unstable angina pectoris\t\t683\t40.18%\r\nMissing\t\t\t\t\t51\t3.00%\r\n8. Heredity on CHD (IBS_NASL): Nominal\r\n\t\t\tCases\tFraction\r\n0: isnâ€™t burdened\t45\t2.65%\r\n1: burdened\t\t27\t1.59%\r\nMissing\t\t\t1628\t95.76%\r\n9. Presence of an essential hypertension (GB): Ordinal\r\n\t\t\t\t\tCases\tFraction\r\n0: there is no essential hypertension\t605\t35.59%\r\n1: Stage 1\t\t\t\t11\t0.65%\r\n2: Stage 2\t\t\t\t880\t51.76%\r\n3: Stage 3\t\t\t\t195\t11.47%\r\nMissing\t\t\t\t\t9\t0.53%\r\n10. Symptomatic hypertension (SIM_GIPERT): Nominal\r\n\t\t\tCases\tFraction\r\n0: no\t\t1635\t96.18%\r\n1: yes\t\t57\t3.35%\r\nMissing\t\t8\t0.47%\r\n11. Duration of arterial hypertension (DLIT_AG): Ordinal\r\n\t\t\t\t\tCases\tFraction\r\n0: there was no arterial hypertension\t551\t32.41%\r\n1: one year\t\t\t\t93\t5.47%\r\n2: two years\t\t\t\t58\t3.41%\r\n3: three years\t\t\t\t58\t3.41%\r\n4: four years\t\t\t\t22\t1.29%\r\n5: five years\t\t\t\t73\t4.29%\r\n6: 6-10 years\t\t\t\t165\t9.71%\r\n7: more than 10 years\t\t\t432\t25.41%\r\nMissing\t\t\t\t\t248\t14.59%\r\n12. Presence of chronic Heart failure (HF) in the anamnesis (ZSN_A): Partially ordered attribute: there are two lines of severities:\r\n0<1<2<4,\r\n0<1<3<4.\r\nState 4 means simultaneous states 2 and 3\r\n\t\t\t\t\t\t\tCases\tFraction\r\n0: there is no chronic heart failure\t\t\t1468\t86.35%\r\n1: I stage\t\t\t\t\t\t103\t6.06%\r\n2: IIÐ stage (heart failure due to right \r\nventricular systolic dysfunction)\t\t\t27\t1.59%\r\n3: IIÐ stage (heart failure due to left \r\nventricular systolic dysfunction)\t\t\t29\t1.71%\r\n4: IIB stage (heart failure due to left and\r\n right ventricular systolic dysfunction)\t\t19\t1.12%\r\nMissing\t\t\t\t\t\t\t54\t3.18%\r\n13. Observing of arrhythmia in the anamnesis (nr11): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1637\t96.29%\r\n1: yes\t\t42\t2.47%\r\nMissing\t\t21\t1.24%\r\n14. Premature atrial contractions in the anamnesis (nr01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1675\t98.53%\r\n1: yes\t\t4\t0.24%\r\nMissing\t\t21\t1.24%\r\n15. Premature ventricular contractions in the anamnesis (nr02): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1660\t97.65%\r\n1: yes\t\t19\t1.12%\r\nMissing\t\t21\t1.24%\r\n16. Paroxysms of atrial fibrillation in the anamnesis (nr03): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1644\t96.71%\r\n1: yes\t\t35\t2.06%\r\nMissing\t\t21\t1.24%\r\n17. A persistent form of atrial fibrillation in the anamnesis (nr04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1650\t97.06%\r\n1: yes\t\t29\t1.71%\r\nMissing\t\t21\t1.24%\r\n18. Ventricular fibrillation in the anamnesis (nr07): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1678\t98.71%\r\n1: yes\t\t1\t0.06%\r\nMissing\t\t21\t1.24%\r\n19. Ventricular paroxysmal tachycardia in the anamnesis (nr08): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1675\t98.53%\r\n1: yes\t\t4\t0.24%\r\nMissing\t\t21\t1.24%\r\n20. First-degree AV block in the anamnesis (np01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1680\t98.82%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t18\t1.06%\r\n21. Third-degree AV block in the anamnesis (np04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1679\t98.76%\r\n1: yes\t\t3\t0.18%\r\nMissing\t\t18\t1.06%\r\n22. LBBB (anterior branch) in the anamnesis (np05): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1671\t98.29%\r\n1: yes\t\t11\t0.65%\r\nMissing\t\t18\t1.06%\r\n23. Incomplete LBBB in the anamnesis (np07): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1681\t98.88%\r\n1: yes\t\t1\t0.06%\r\nMissing\t\t18\t1.06%\r\n24. Complete LBBB in the anamnesis (np08): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1676\t98.59%\r\n1: yes\t\t6\t0.35%\r\nMissing\t\t18\t1.06%\r\n25. Incomplete RBBB in the anamnesis (np09): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1680\t98.82%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t18\t1.06%\r\n26. Complete RBBB in the anamnesis (np10): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1679\t98.76%\r\n1: yes\t\t3\t0.18%\r\nMissing\t\t18\t1.06%\r\n27. Diabetes mellitus in the anamnesis (endocr_01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1461\t85.94%\r\n1: yes\t\t228\t13.41%\r\nMissing\t\t11\t0.65%\r\n28. Obesity in the anamnesis (endocr_02): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1648\t96.94%\r\n1: yes\t\t42\t2.47%\r\nMissing\t\t10\t0.59%\r\n29. Thyrotoxicosis in the anamnesis (endocr_03): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1677\t98.65%\r\n1: yes\t\t13\t0.76%\r\nMissing\t\t10\t0.59%\t\r\n30. Chronic bronchitis in the anamnesis (zab_leg_01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1559\t91.71%\r\n1: yes\t\t134\t7.88%\r\nMissing\t\t7\t0.41%\r\n31.Obstructive chronic bronchitis in the anamnesis (zab_leg_02): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1572\t92.47%\r\n1: yes\t\t121\t7.12%\r\nMissing\t\t7\t0.41%\r\n32. Bronchial asthma in the anamnesis (zab_leg_03): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1656\t97.41%\r\n1: yes\t\t37\t2.18%\r\nMissing\t\t7\t0.41%\r\n33. Chronic pneumonia in the anamnesis (zab_leg_04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1684\t99.06%\r\n1: yes\t\t9\t0.53%\r\nMissing\t\t7\t0.41%\r\n34. Pulmonary tuberculosis in the anamnesis (zab_leg_06): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1684\t99.06%\r\n1: yes\t\t9\t0.53%\r\nMissing\t\t7\t0.41%\r\n35. Systolic blood pressure according to Emergency Cardiology Team (S_AD_KBRIG) (mmHg): Real.\r\n36. Diastolic blood pressure according to Emergency Cardiology Team (D_AD_KBRIG) (mmHg): Real.\r\n37. Systolic blood pressure according to intensive care unit (S_AD_ORIT) (mmHg): Real.\r\n38. Diastolic blood pressure according to intensive care unit (D_AD_ORIT) (mmHg): Real.\r\n39. Pulmonary edema at the time of admission to intensive care unit (O_L_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1578\t92.82%\r\n1: yes\t\t110\t6.47%\r\nMissing\t\t12\t0.71%\r\n40. Cardiogenic shock at the time of admission to intensive care unit (K_SH_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1639\t96.41%\r\n1: yes\t\t46\t2.71%\r\nMissing\t\t15\t0.88%\r\n41. Paroxysms of atrial fibrillation at the time of admission to intensive care unit, (or at a pre-hospital stage) (MP_TP_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1572\t92.47%\r\n1: yes\t\t114\t6.71%\r\nMissing\t\t14\t0.82%\r\n42. Paroxysms of supraventricular tachycardia at the time of admission to intensive care unit, (or at a pre-hospital stage) (SVT_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1680\t98.82%\r\n1: yes\t\t8\t0.47%\r\nMissing\t\t12\t0.71%\r\n43. Paroxysms of ventricular tachycardia at the time of admission to intensive care unit, (or at a pre-hospital stage) (GT_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1680\t98.82%\r\n1: yes\t\t8\t0.47%\r\nMissing\t\t12\t0.71%\r\n44. Ventricular fibrillation at the time of admission to intensive care unit, (or at a pre-hospital stage) (FIB_G_POST): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1673\t98.41%\r\n1: yes\t\t15\t0.88%\r\nMissing\t\t12\t0.71%\r\n45. Presence of an anterior myocardial infarction (left ventricular) (ECG changes in leads V1: V4 ) (ant_im): Ordinal\r\n\t\t\t\t\t\tCases\tFraction\r\n0: there is no infarct in this location\t660\t38.82%\r\n1: QRS has no changes\t\t\t\t392\t23.06%\r\n2: QRS is like QR-complex\t\t\t39\t2.29%\r\n3: QRS is like Qr-complex\t\t\t34\t2.00%\r\n4: QRS is like QS-complex\t\t\t492\t28.94%\r\nMissing\t\t\t\t\t\t83\t4.88%\r\n46. Presence of a lateral myocardial infarction (left ventricular) (ECG changes in leads V5: V6 , I, AVL) (lat_im): Ordinal\r\n\t\t\t\t\tCases\tFraction\r\n0: there is no infarct in this location\t576\t33.88%\r\n1: QRS has no changes\t\t\t838\t49.29%\r\n2: QRS is like QR-complex\t\t97\t5.71%\r\n3: QRS is like Qr-complex\t\t72\t4.24%\r\n4: QRS is like QS-complex\t\t37\t2.18%\r\nMissing\t\t\t\t\t80\t4.71%\r\n47. Presence of an inferior myocardial infarction (left ventricular) (ECG changes in leads III, AVF, II). (inf_im): Ordinal\r\n\t\t\t\t\t\tCases\tFraction\r\n0: there is no infarct in this location\t937\t55.12%\r\n1: QRS has no changes\t\t\t\t195\t11.47%\r\n2: QRS is like QR-complex\t\t\t191\t11.24%\r\n3: QRS is like Qr-complex\t\t\t121\t7.12%\r\n4: QRS is like QS-complex\t\t\t176\t10.35%\r\nMissing\t\t\t\t\t\t80\t4.71%\r\n48. Presence of a posterior myocardial infarction (left ventricular) (ECG changes in V7: V9, reciprocity changes in leads V1 â€“ V3) (post_im): Ordinal\r\n\t\t\t\t\t\tCases\tFraction\r\n0: there is no infarct in this location\t1370\t80.59%\r\n1: QRS has no changes\t\t\t\t157\t9.24%\r\n2: QRS is like QR-complex\t\t\t52\t3.06%\r\n3: QRS is like Qr-complex\t\t\t35\t2.06%\r\n4: QRS is like QS-complex\t\t\t14\t0.82%\r\nMissing\t\t\t\t\t\t72\t4.24%\r\n49. Presence of a right ventricular myocardial infarction (IM_PG_P): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1649\t97.00%\r\n1: yes\t\t50\t2.94%\r\nMissing\t\t1\t0.06%\r\n50. ECG rhythm at the time of admission to hospital: sinus (with a heart rate 60-90) (ritm_ecg_p_01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t519\t30.53%\r\n1: yes\t\t1029\t60.53%\r\nMissing\t\t152\t8.94%\r\n51. ECG rhythm at the time of admission to hospital: atrial fibrillation (ritm_ecg_p_02): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1453\t85.47%\r\n1: yes\t\t95\t5.59%\r\nMissing\t\t152\t8.94%\r\n52. ECG rhythm at the time of admission to hospital: atrial (ritm_ecg_p_04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1525\t89.71%\r\n1: yes\t\t23\t1.35%\r\nMissing\t\t152\t8.94%\r\n53. ECG rhythm at the time of admission to hospital: idioventricular (ritm_ecg_p_06): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1547\t91.00%\r\n1: yes\t\t1\t0.06%\r\nMissing\t\t152\t8.94%\r\n54. ECG rhythm at the time of admission to hospital: sinus with a heart rate above 90 (tachycardia) (ritm_ecg_p_07): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1195\t70.29%\r\n1: yes\t\t353\t20.76%\r\nMissing\t\t152\t8.94%\r\n55. ECG rhythm at the time of admission to hospital: sinus with a heart rate below 60 (bradycardia) (ritm_ecg_p_08): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1502\t88.35%\r\n1: yes\t\t46\t2.71%\r\nMissing\t\t152\t8.94%\r\n56. Premature atrial contractions on ECG at the time of admission to hospital (n_r_ecg_p_01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1527\t89.82%\r\n1: yes\t\t58\t3.41%\r\nMissing\t\t115\t6.76%\r\n57. Frequent premature atrial contractions on ECG at the time of admission to hospital (n_r_ecg_p_02): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1577\t92.76%\r\n1: yes\t\t8\t0.47%\r\nMissing\t\t115\t6.76%\r\n58.Premature ventricular contractions on ECG at the time of admission to hospital (n_r_ecg_p_03): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1381\t81.24%\r\n1: yes\t\t204\t12.00%\r\nMissing\t\t115\t6.76%\r\n59. Frequent premature ventricular contractions on ECG at the time of admission to hospital (n_r_ecg_p_04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1516\t89.18%\r\n1: yes\t\t69\t4.06%\r\nMissing\t\t115\t6.76%\r\n60. Paroxysms of atrial fibrillation on ECG at the time of admission to hospital (n_r_ecg_p_05): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1515\t89.12%\r\n1: yes\t\t70\t4.12%\r\nMissing\t\t115\t6.76%\r\n61. Persistent form of atrial fibrillation on ECG at the time of admission to hospital (n_r_ecg_p_06): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1553\t91.35%\r\n1: yes\t\t32\t1.88%\r\nMissing\t\t115\t6.76%\r\n62. Paroxysms of supraventricular tachycardia on ECG at the time of admission to hospital (n_r_ecg_p_08): Nominal \r\n\t\tCases\tFraction\r\n0: no\t\t1581\t93.00%\r\n1: yes\t\t4\t0.24%\r\nMissing\t\t115\t6.76%\r\n63. Paroxysms of ventricular tachycardia on ECG at the time of admission to hospital (n_r_ecg_p_09): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1583\t93.12%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t115\t6.76%\r\n64. Ventricular fibrillation on ECG at the time of admission to hospital (n_r_ecg_p_10): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1583\t93.12%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t115\t6.76%\r\n65. Sinoatrial block on ECG at the time of admission to hospital (n_p_ecg_p_01): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1583\t93.12%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t115\t6.76%\r\n66. First-degree AV block on ECG at the time of admission to hospital (n_p_ecg_p_03): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1553\t91.35%\r\n1: yes\t\t32\t1.88%\r\nMissing\t\t115\t6.76%\r\n67. Type 1 Second-degree AV block (Mobitz I/Wenckebach) on ECG at the time of admission to hospital (n_p_ecg_p_04): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1580\t92.94%\r\n1: yes\t\t5\t0.29%\r\nMissing\t\t115\t6.76%\r\n68. Type 2 Second-degree AV block (Mobitz II/Hay) on ECG at the time of admission to hospital (n_p_ecg_p_05): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1583\t93.12%\r\n1: yes\t\t2\t0.12%\r\nMissing\t\t115\t6.76%\r\n69. Third-degree AV block on ECG at the time of admission to hospital (n_p_ecg_p_06): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1558\t91.65%\r\n1: yes\t\t27\t1.59%\r\nMissing\t\t115\t6.76%\r\n70. LBBB (anterior branch) on ECG at the time of admission to hospital (n_p_ecg_p_07): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1483\t87.24%\r\n1: yes\t\t102\t6.00%\r\nMissing\t\t115\t6.76%\r\n71. LBBB (posterior branch) on ECG at the time of admission to hospital (n_p_ecg_p_08): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1578\t92.82%\r\n1: yes\t\t7\t0.41%\r\nMissing\t\t115\t6.76%\r\n72. Incomplete LBBB on ECG at the time of admission to hospital (n_p_ecg_p_09): Nominal\r\n\t\tCases\tFraction\r\n0: no\t\t1575\t92.65%\r\n1: yes\t\t10\t0.59%\r\nMissing\t\t115\t6.76%\r\n73. Complete LBBB on ECG at the time of admission to hospital (n_p_

,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,DLIT_AG,...,NOT_NA_1_n,NOT_NA_2_n,NOT_NA_3_n,LID_S_n,B_BLOK_S_n,ANT_CA_S_n,GEPAR_S_n,ASP_S_n,TIKL_S_n,TRENT_S_n
0,77.0,1,2.0,1.0,1.0,2.0,NaN,3.0,0.0,7.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
1,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
2,52.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,2.0,...,3.0,2.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0
3,68.0,0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
4,60.0,1,0.0,0.0,0.0,2.0,NaN,3.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

,name,role,type,demographic,description,units,missing_values
0,ID,ID,Integer,None,Record ID (ID): Unique identifier. Cannot be related to participant. It can be used for reference only.,None,no
1,AGE,Feature,Integer,Age,Age of patient.,None,no
2,SEX,Feature,Binary,Sex,"0: female, 1: male",None,no
3,INF_ANAM,Feature,Categorical,None,Quantity of myocardial infarctions in the anamnesis. \n\n0: zero\n\n1: one\n\n2: two\n\n3: three and more,None,yes
4,STENOK_AN,Feature,Categorical,None,Exertional angina pectoris in the anamnesis. \n\n0: never\n\n1: during the last year \n\n2: one year ago\n\n3: two years ago\n\n4: three years ago\n\n5: 4-5 years ago,None,yes
...,...,...,...,...,...,...,...
119,DRESSLER,Target,Binary,None,Dressler syndrome,None,no
120,ZSN,Target,Binary,None,Chronic heart failure,None,no
121,REC_IM,Target,Binary,None,Relapse of the myocardial infarction,None,no
122,P_IM_STEN,Target,Binary,None,Post-infarction angina,None,no
123,LET_IS,Target,Categorical,None,Lethal outcome (cause)\n\n0: unknown (alive)\n\n1: cardiogenic shock\n\n2: pulmonary edema\n\n3: myocardial rupture\n\n4: progress of congestive heart failure\n\n5: thromboembolism\n\n6: asystole\n\n7: ventricular fibrillation,None,no

pandas.DataFrame shape: (1700, 111)

           Card    %_Card NaN_Values %_NaN_Values     Type               Class
AGE          62  3.647059          8     0.470588  float64  Numeric - Discrete
SEX           2  0.117647          0          0.0    int64              Binary
INF_ANAM      4  0.235294          4     0.235294  float64           Categoric
STENOK_AN     7  0.411765        106     6.235294  float64           Categoric
FK_STENOK     5  0.294118         73     4.294118  float64           Categoric
...         ...       ...        ...          ...      ...                 ...
ANT_CA_S_n    2  0.117647         13     0.764706  float64              Binary
GEPAR_S_n     2  0.117647         17          1.0  float64              Binary
ASP_S_n       2  0.117647         17          1.0  float64              Binary
TIKL_S_n      2  0.117647         16     0.941176  float64              Binary
TRENT_S_n     2  0.117647         16     0.941176  float64              Binary

[111 rows x 6 columns]

# Myocardial infarction complications

Golovenkin, S., Shulman, V., Rossiev, D., Shesternya, P., Nikulina, S., Orlova, Y., & Voino-Yasenetsky, V. (2020). Myocardial infarction complications [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C53P5M.

In [16]:
 
# fetch dataset 
mammographic_mass = fetch_ucirepo(id=161) 
  
# data (as pandas dataframes) 
X = mammographic_mass.data.features 
y = mammographic_mass.data.targets 
  
# metadata 
print(mammographic_mass.metadata) 
display(X)
# variable information 
print(mammographic_mass.variables) 
ds.get_cardinality(X)

{'uci_id': 161, 'name': 'Mammographic Mass', 'repository_url': 'https://archive.ics.uci.edu/dataset/161/mammographic+mass', 'data_url': 'https://archive.ics.uci.edu/static/public/161/data.csv', 'abstract': "Discrimination of benign and malignant mammographic masses based on BI-RADS attributes and the patient's age.", 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 961, 'num_features': 5, 'feature_types': ['Integer'], 'demographics': ['Age'], 'target_col': ['Severity'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2007, 'last_updated': 'Thu Mar 28 2024', 'dataset_doi': '10.24432/C53K6Z', 'creators': ['Matthias Elter'], 'intro_paper': {'ID': 448, 'type': 'NATIVE', 'title': 'The prediction of breast cancer biopsy outcomes using two CAD approaches that both emphasize an intelligible decision process.', 'authors': 'M. Elter, R. Schulz-Wendtland, T. Wittenberg', 'venue': 'Medical Physics (Lancaster)', 'year': 2007, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/The-prediction-of-breast-cancer-biopsy-outcomes-two-Elter-Schulz-Wendtland/48666ddd437ca7bda95899d2ed1d0ae1ad58c9d0', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "Mammography is the most effective method for breast cancer screening\r\navailable today. However, the low positive predictive value of breast\r\nbiopsy resulting from mammogram interpretation leads to approximately\r\n70% unnecessary biopsies with benign outcomes. To reduce the high\r\nnumber of unnecessary breast biopsies, several computer-aided diagnosis\r\n(CAD) systems have been proposed in the last years.These systems\r\nhelp physicians in their decision to perform a breast biopsy on a suspicious\r\nlesion seen in a mammogram or to perform a short term follow-up\r\nexamination instead.\r\nThis data set can be used to predict the severity (benign or malignant)\r\nof a mammographic mass lesion from BI-RADS attributes and the patient's age.\r\nIt contains a BI-RADS assessment, the patient's age and three BI-RADS attributes\r\ntogether with the ground truth (the severity field) for 516 benign and\r\n445 malignant masses that have been identified on full field digital mammograms\r\ncollected at the Institute of Radiology of the\r\nUniversity Erlangen-Nuremberg between 2003 and 2006.\r\nEach instance has an associated BI-RADS assessment ranging from 1 (definitely benign)\r\nto 5 (highly suggestive of malignancy) assigned in a double-review process by\r\nphysicians. Assuming that all cases with BI-RADS assessments greater or equal\r\na given value (varying from 1 to 5), are malignant and the other cases benign,\r\nsensitivities and associated specificities can be calculated. These can be an\r\nindication of how well a CAD system performs compared to the radiologists.\r\n\r\nClass Distribution: benign: 516; malignant: 445\r\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "6 Attributes in total (1 goal field, 1 non-predictive, 4 predictive attributes)\r\n\r\n1. BI-RADS assessment: 1 to 5 (ordinal, non-predictive!)  \r\n2. Age: patient's age in years (integer)\r\n3. Shape: mass shape: round=1 oval=2 lobular=3 irregular=4 (nominal)\r\n4. Margin: mass margin: circumscribed=1 microlobulated=2 obscured=3 ill-defined=4 spiculated=5 (nominal)\r\n5. Density: mass density high=1 iso=2 low=3 fat-containing=4 (ordinal)\r\n6. Severity: benign=0 or malignant=1 (binominal, goal field!)\r\n\r\n\r\nMissing Attribute Values:\r\n    - BI-RADS assessment:    2\r\n    - Age:                   5\r\n    - Shape:                31\r\n    - Margin:               48\r\n    - Density:              76\r\n    - Severity:              0\r\n", 'citation': None}}

     BI-RADS   Age  Shape  Margin  Density
0        5.0  67.0    3.0     5.0      3.0
1        4.0  43.0    1.0     1.0      NaN
2        5.0  58.0    4.0     5.0      3.0
3        4.0  28.0    1.0     1.0      3.0
4        5.0  74.0    1.0     5.0      NaN
..       ...   ...    ...     ...      ...
956      4.0  47.0    2.0     1.0      3.0
957      4.0  56.0    4.0     5.0      3.0
958      4.0  64.0    4.0     5.0      3.0
959      5.0  66.0    4.0     5.0      3.0
960      4.0  62.0    3.0     3.0      3.0

[961 rows x 5 columns]

       name     role     type demographic description units missing_values
0   BI-RADS  Feature  Integer        None        None  None            yes
1       Age  Feature  Integer         Age        None  None            yes
2     Shape  Feature  Integer        None        None  None            yes
3    Margin  Feature  Integer        None        None  None            yes
4   Density  Feature  Integer        None        None  None            yes
5  Severity   Target   Binary        None        None  None             no
pandas.DataFrame shape: (961, 5)

        Card    %_Card NaN_Values %_NaN_Values     Type               Class
BI-RADS    7  0.728408          2     0.208117  float64           Categoric
Age       73  7.596254          5     0.520291  float64  Numeric - Discrete
Shape      4  0.416233         31     3.225806  float64           Categoric
Margin     5  0.520291         48     4.994797  float64           Categoric
Density    4  0.416233         76     7.908429  float64           Categoric

# Mammographic Mass

Elter, M. (2007). Mammographic Mass [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C53K6Z.

In [17]:
# fetch dataset 
mammographic_mass = fetch_ucirepo(id=161) 
  
# data (as pandas dataframes) 
X = mammographic_mass.data.features 
y = mammographic_mass.data.targets 
  
# metadata 
print(mammographic_mass.metadata) 
display(X)
print(mammographic_mass.variables) 
ds.get_cardinality(X)

{'uci_id': 161, 'name': 'Mammographic Mass', 'repository_url': 'https://archive.ics.uci.edu/dataset/161/mammographic+mass', 'data_url': 'https://archive.ics.uci.edu/static/public/161/data.csv', 'abstract': "Discrimination of benign and malignant mammographic masses based on BI-RADS attributes and the patient's age.", 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 961, 'num_features': 5, 'feature_types': ['Integer'], 'demographics': ['Age'], 'target_col': ['Severity'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2007, 'last_updated': 'Thu Mar 28 2024', 'dataset_doi': '10.24432/C53K6Z', 'creators': ['Matthias Elter'], 'intro_paper': {'ID': 448, 'type': 'NATIVE', 'title': 'The prediction of breast cancer biopsy outcomes using two CAD approaches that both emphasize an intelligible decision process.', 'authors': 'M. Elter, R. Schulz-Wendtland, T. Wittenberg', 'venue': 'Medical Physics (Lancaster)', 'year': 2007, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/The-prediction-of-breast-cancer-biopsy-outcomes-two-Elter-Schulz-Wendtland/48666ddd437ca7bda95899d2ed1d0ae1ad58c9d0', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "Mammography is the most effective method for breast cancer screening\r\navailable today. However, the low positive predictive value of breast\r\nbiopsy resulting from mammogram interpretation leads to approximately\r\n70% unnecessary biopsies with benign outcomes. To reduce the high\r\nnumber of unnecessary breast biopsies, several computer-aided diagnosis\r\n(CAD) systems have been proposed in the last years.These systems\r\nhelp physicians in their decision to perform a breast biopsy on a suspicious\r\nlesion seen in a mammogram or to perform a short term follow-up\r\nexamination instead.\r\nThis data set can be used to predict the severity (benign or malignant)\r\nof a mammographic mass lesion from BI-RADS attributes and the patient's age.\r\nIt contains a BI-RADS assessment, the patient's age and three BI-RADS attributes\r\ntogether with the ground truth (the severity field) for 516 benign and\r\n445 malignant masses that have been identified on full field digital mammograms\r\ncollected at the Institute of Radiology of the\r\nUniversity Erlangen-Nuremberg between 2003 and 2006.\r\nEach instance has an associated BI-RADS assessment ranging from 1 (definitely benign)\r\nto 5 (highly suggestive of malignancy) assigned in a double-review process by\r\nphysicians. Assuming that all cases with BI-RADS assessments greater or equal\r\na given value (varying from 1 to 5), are malignant and the other cases benign,\r\nsensitivities and associated specificities can be calculated. These can be an\r\nindication of how well a CAD system performs compared to the radiologists.\r\n\r\nClass Distribution: benign: 516; malignant: 445\r\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "6 Attributes in total (1 goal field, 1 non-predictive, 4 predictive attributes)\r\n\r\n1. BI-RADS assessment: 1 to 5 (ordinal, non-predictive!)  \r\n2. Age: patient's age in years (integer)\r\n3. Shape: mass shape: round=1 oval=2 lobular=3 irregular=4 (nominal)\r\n4. Margin: mass margin: circumscribed=1 microlobulated=2 obscured=3 ill-defined=4 spiculated=5 (nominal)\r\n5. Density: mass density high=1 iso=2 low=3 fat-containing=4 (ordinal)\r\n6. Severity: benign=0 or malignant=1 (binominal, goal field!)\r\n\r\n\r\nMissing Attribute Values:\r\n    - BI-RADS assessment:    2\r\n    - Age:                   5\r\n    - Shape:                31\r\n    - Margin:               48\r\n    - Density:              76\r\n    - Severity:              0\r\n", 'citation': None}}

     BI-RADS   Age  Shape  Margin  Density
0        5.0  67.0    3.0     5.0      3.0
1        4.0  43.0    1.0     1.0      NaN
2        5.0  58.0    4.0     5.0      3.0
3        4.0  28.0    1.0     1.0      3.0
4        5.0  74.0    1.0     5.0      NaN
..       ...   ...    ...     ...      ...
956      4.0  47.0    2.0     1.0      3.0
957      4.0  56.0    4.0     5.0      3.0
958      4.0  64.0    4.0     5.0      3.0
959      5.0  66.0    4.0     5.0      3.0
960      4.0  62.0    3.0     3.0      3.0

[961 rows x 5 columns]

       name     role     type demographic description units missing_values
0   BI-RADS  Feature  Integer        None        None  None            yes
1       Age  Feature  Integer         Age        None  None            yes
2     Shape  Feature  Integer        None        None  None            yes
3    Margin  Feature  Integer        None        None  None            yes
4   Density  Feature  Integer        None        None  None            yes
5  Severity   Target   Binary        None        None  None             no
pandas.DataFrame shape: (961, 5)

        Card    %_Card NaN_Values %_NaN_Values     Type               Class
BI-RADS    7  0.728408          2     0.208117  float64           Categoric
Age       73  7.596254          5     0.520291  float64  Numeric - Discrete
Shape      4  0.416233         31     3.225806  float64           Categoric
Margin     5  0.520291         48     4.994797  float64           Categoric
Density    4  0.416233         76     7.908429  float64           Categoric

# Cardiotocography

Campos, D. & Bernardes, J. (2000). Cardiotocography [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C51S4N.

In [18]:
# fetch dataset 
cardiotocography = fetch_ucirepo(id=193) 
  
# data (as pandas dataframes) 
X = cardiotocography.data.features 
y = cardiotocography.data.targets 
  
# metadata 
print(cardiotocography.metadata) 
display(X.head())
print(cardiotocography.variables) 
ds.get_cardinality(X)

{'uci_id': 193, 'name': 'Cardiotocography', 'repository_url': 'https://archive.ics.uci.edu/dataset/193/cardiotocography', 'data_url': 'https://archive.ics.uci.edu/static/public/193/data.csv', 'abstract': 'The dataset consists of measurements of fetal heart rate (FHR) and uterine contraction (UC) features on cardiotocograms classified by expert obstetricians.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 2126, 'num_features': 21, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['CLASS', 'NSP'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2000, 'last_updated': 'Fri Mar 15 2024', 'dataset_doi': '10.24432/C51S4N', 'creators': ['D. Campos', 'J. Bernardes'], 'intro_paper': None, 'additional_info': {'summary': '2126 fetal cardiotocograms (CTGs) were automatically processed and the respective diagnostic features measured. The CTGs were also classified by three expert obstetricians and a consensus classification label assigned to each of them. Classification was both with respect to a morphologic pattern (A, B, C. ...) and to a fetal state (N, S, P). Therefore the dataset can be used either for 10-class or 3-class experiments.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'LB - FHR baseline (beats per minute)\r\nAC - # of accelerations per second\r\nFM - # of fetal movements per second\r\nUC - # of uterine contractions per second\r\nDL - # of light decelerations per second\r\nDS - # of severe decelerations per second\r\nDP - # of prolongued decelerations per second\r\nASTV - percentage of time with abnormal short term variability\r\nMSTV - mean value of short term variability\r\nALTV - percentage of time with abnormal long term variability\r\nMLTV - mean value of long term variability\r\nWidth - width of FHR histogram\r\nMin - minimum of FHR histogram\r\nMax - Maximum of FHR histogram\r\nNmax - # of histogram peaks\r\nNzeros - # of histogram zeros\r\nMode - histogram mode\r\nMean - histogram mean\r\nMedian - histogram median\r\nVariance - histogram variance\r\nTendency - histogram tendency\r\nCLASS - FHR pattern class code (1 to 10) \r\nNSP - fetal state class code (N=normal; S=suspect; P=pathologic)', 'citation': None}}

,LB,AC,FM,UC,DL,DS,DP,ASTV,MSTV,ALTV,...,Width,Min,Max,Nmax,Nzeros,Mode,Mean,Median,Variance,Tendency
0,120,0.000,0.0,0.000,0.000,0.0,0.0,73,0.5,43,...,64,62,126,2,0,120,137,121,73,1
1,132,0.006,0.0,0.006,0.003,0.0,0.0,17,2.1,0,...,130,68,198,6,1,141,136,140,12,0
2,133,0.003,0.0,0.008,0.003,0.0,0.0,16,2.1,0,...,130,68,198,5,1,141,135,138,13,0
3,134,0.003,0.0,0.008,0.003,0.0,0.0,16,2.4,0,...,117,53,170,11,0,137,134,137,13,1
4,132,0.007,0.0,0.008,0.000,0.0,0.0,16,2.4,0,...,117,53,170,9,0,137,136,138,11,1

        name     role        type demographic description units missing_values
0         LB  Feature     Integer        None        None  None             no
1         AC  Feature  Continuous        None        None  None             no
2         FM  Feature  Continuous        None        None  None             no
3         UC  Feature  Continuous        None        None  None             no
4         DL  Feature  Continuous        None        None  None             no
5         DS  Feature  Continuous        None        None  None             no
6         DP  Feature  Continuous        None        None  None             no
7       ASTV  Feature     Integer        None        None  None             no
8       MSTV  Feature  Continuous        None        None  None             no
9       ALTV  Feature     Integer        None        None  None             no
10      MLTV  Feature  Continuous        None        None  None             no
11     Width  Feature     Integer        None        None  None             no
12       Min  Feature     Integer        None        None  None             no
13       Max  Feature     Integer        None        None  None             no
14      Nmax  Feature     Integer        None        None  None             no
15    Nzeros  Feature     Integer        None        None  None             no
16      Mode  Feature     Integer        None        None  None             no
17      Mean  Feature     Integer        None        None  None             no
18    Median  Feature     Integer        None        None  None             no
19  Variance  Feature     Integer        None        None  None             no
20  Tendency  Feature     Integer        None        None  None             no
21     CLASS   Target     Integer        None        None  None             no
22       NSP   Target     Integer        None        None  None             no
pandas.DataFrame shape: (2126, 21)

         Card     %_Card NaN_Values %_NaN_Values     Type               Class
LB         48   2.257761          0          0.0    int64  Numeric - Discrete
AC         20   0.940734          0          0.0  float64  Numeric - Discrete
FM        102   4.797742          0          0.0  float64  Numeric - Discrete
UC         16   0.752587          0          0.0  float64  Numeric - Discrete
DL         16   0.752587          0          0.0  float64  Numeric - Discrete
DS          2   0.094073          0          0.0  float64              Binary
DP          6    0.28222          0          0.0  float64           Categoric
ASTV       75   3.527752          0          0.0    int64  Numeric - Discrete
MSTV       57   2.681091          0          0.0  float64  Numeric - Discrete
ALTV       87   4.092192          0          0.0    int64  Numeric - Discrete
MLTV      249  11.712135          0          0.0  float64  Numeric - Discrete
Width     154    7.24365          0          0.0    int64  Numeric - Discrete
Min       109   5.126999          0          0.0    int64  Numeric - Discrete
Max        86   4.045155          0          0.0    int64  Numeric - Discrete
Nmax       18    0.84666          0          0.0    int64  Numeric - Discrete
Nzeros      9    0.42333          0          0.0    int64           Categoric
Mode       88   4.139229          0          0.0    int64  Numeric - Discrete
Mean      103   4.844779          0          0.0    int64  Numeric - Discrete
Median     95   4.468485          0          0.0    int64  Numeric - Discrete
Variance  133    6.25588          0          0.0    int64  Numeric - Discrete
Tendency    3    0.14111          0          0.0    int64           Categoric

In [19]:
y['CLASS'].value_counts()

CLASS
2     579
1     384
6     332
7     252
10    197
8     107
4      81
5      72
9      69
3      53
Name: count, dtype: int64

In [20]:
y['NSP'].value_counts()

NSP
1    1655
2     295
3     176
Name: count, dtype: int64